// Journal batch C: gifting and occasions (Pillar F) and business and partnerships (Pillar G).
// Rules: easy English (grade 6 to 8), short sentences, facts only from the client brief, the site flows or the
// sources listed per post. No prices, fees, lead times or dates are promised: they are confirmed on WhatsApp.
//
// INTEGRATION NOTES for the step that renders these posts:
// 1. BatchPost is the Post type from ../journal with two changes: `blocks` also allows { t: "image"; slot } markers,
//    and each post has an `images` array of four entries (hero, inline-1, inline-2, inline-3).
// 2. The renderer must replace each { t: "image", slot } block with the image whose `slot` matches in `images`.
//    The hero image is not a block: it replaces `cover` on the post page. Until real photos exist, `cover` is the
//    closest existing PhotoId and inline images should be skipped or filled from `images[].brief`.
// 3. `links` lists the internal pages each post points to (the Block type has no link block). Render them as a
//    "Related pages" list under the body, or turn the labels into inline links.
// 4. `description` is the meta description (150 characters or fewer). `excerpt` has the same text.
import type { Block, Post } from "../journal/legacy";

export type ImageSlot = "hero" | "inline-1" | "inline-2" | "inline-3";

export type ImageSpec = {
  slot: ImageSlot;
  /** Heading text the image follows. null for the hero. */
  after: string | null;
  /** What the photo should show, in plain words. */
  brief: string;
  /** What a screen reader should hear. */
  altHint: string;
};

export type BatchBlock = Block | { t: "image"; slot: Exclude<ImageSlot, "hero"> };

export type BatchPost = Omit<Post, "blocks"> & {
  blocks: BatchBlock[];
  description: string;
  readTime: string;
  tags: string[];
  images: ImageSpec[];
  sources: string[];
  links: { label: string; href: string }[];
};

const i1: BatchBlock = { t: "image", slot: "inline-1" };
const i2: BatchBlock = { t: "image", slot: "inline-2" };
const i3: BatchBlock = { t: "image", slot: "inline-3" };

export const postsC: BatchPost[] = [
  {
    slug: "baby-shower-gifts-from-nairobi",
    title: "Baby shower gifts from Nairobi",
    excerpt: "How to pick a crocheted animal for a baby shower: colour, animal and size, what we do not claim, and how to order on WhatsApp.",
    description: "How to pick a crocheted animal for a baby shower: colour, animal and size, what we do not claim, and how to order on WhatsApp.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Baby shower", "Colour", "Size"],
    cover: "giraffeTrio",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "A baby shower gift should be easy to wrap and easy to carry. It should also look good on a shelf after the party. A crocheted animal from Nairobi can do all three. You only need to choose a colour, an animal and a size." },
      { t: "h", text: "Start with colour" },
      { t: "p", text: "Some parents keep the baby's sex a secret. Colour can keep your gift open. The elephants come in grey, caramel brown, slate blue, lavender and dusty purple. Our giraffes come in yellow, cream, tan and orange." },
      { t: "p", text: "Cream, grey and tan suit most rooms. They say nothing about a boy or a girl." },
      i1,
      { t: "h", text: "Pick the animal" },
      { t: "p", text: "Ask the host about the room. If the theme is safari, an elephant or a giraffe fits at once. If the walls are plain, a rabbit may feel more at home." },
      { t: "p", text: "A lion is good for a guest who loves Kenya's parks. Its long yarn mane gives people something to look at." },
      { t: "h", text: "Pick the size" },
      { t: "p", text: "At a shower, size is about carrying and showing. A small animal fits in a gift bag next to a card. A large one is a gift on its own." },
      { t: "p", text: "Small is the smallest size and Extra large is the largest. If you are unsure, the size finder can help you choose a step." },
      i2,
      { t: "h", text: "What we do not say" },
      { t: "p", text: "We do not say which age an animal suits. We do not say it is made for newborns. That choice belongs to the parents." },
      { t: "p", text: "What we can say is simple. Our plain animals are crocheted from recycled acrylic yarn. They have zero plastic and nothing detachable. You can clean them easily." },
      { t: "h", text: "Give more than one" },
      { t: "ul", items: [
        "Two sizes of the same animal. One is for the baby and one is for a big sister, brother or cousin.",
        "A small family from the family builder. You pick several animals and send one list.",
        "A group gift from friends. Buy one large animal and let everyone sign the card.",
      ] },
      i3,
      { t: "h", text: "Add a note" },
      { t: "p", text: "The order form has a gift note box. Write to the parents. A short welcome is enough. Please leave out the baby's surname, because the note goes inside a WhatsApp message." },
      { t: "h", text: "Tell us the date" },
      { t: "p", text: "Give us the shower date when you message us. We tell you on WhatsApp what is possible. We also confirm the price and any delivery fee there. If the date is too close, we will say so early." },
      { t: "p", text: "Do you want colours to match a theme? Start in the Custom Studio. We check each extra with you first, because not every idea works in crochet." },
      { t: "h", text: "A simple plan for the day" },
      { t: "p", text: "Order a week or two before the party if you can. Ask the host if gifts are opened in front of guests. If they are, a bigger animal makes a nice moment. If not, a small one is easier to pass along." },
      { t: "p", text: "You can also ask us for a second colour of the same animal. Two animals in different colours can go to twins, or to two families who share the party." },
      { t: "p", text: "Wrap the animal in plain paper, tie a ribbon and keep the card short." },
    ],
    cta: { text: "Tell us the shower date and the room colours, and we will suggest an animal.", message: "Hello Mikono Creations, I am looking for a baby shower gift. The shower is on" },
    related: ["choosing-a-size-as-a-gift", "how-custom-orders-work"],
    images: [
      { slot: "hero", after: null, brief: "A cream or grey crocheted elephant on a plain pale table beside a folded card and a ribbon, daylight from the left, no people.", altHint: "A grey crocheted elephant on a table next to a folded card and a ribbon." },
      { slot: "inline-1", after: "Start with colour", brief: "Three colourways of the same animal in a row on a table: cream, grey and tan.", altHint: "Three crocheted elephants in cream, grey and tan side by side." },
      { slot: "inline-2", after: "Pick the size", brief: "A small and a large animal next to a gift bag, to show what fits in the bag.", altHint: "A small and a large crocheted animal beside a paper gift bag." },
      { slot: "inline-3", after: "Give more than one", brief: "A wrapped gift on a table with a hand-written card and a ribbon being tied, hands only.", altHint: "Hands tying a ribbon around a wrapped gift beside a card." },
    ],
    sources: [],
    links: [
      { label: "Elephant", href: "/shop/elephant" },
      { label: "Giraffe", href: "/shop/giraffe" },
      { label: "Rabbit", href: "/shop/rabbit" },
      { label: "Lion", href: "/shop/lion" },
      { label: "Size finder", href: "/size-finder" },
      { label: "Build a family", href: "/build-a-family" },
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Custom Studio", href: "/custom/studio" },
    ],
  },

  {
    slug: "how-custom-orders-work",
    title: "How custom orders work",
    excerpt: "From a first idea to a quote on WhatsApp: the steps of a custom crocheted animal order, and what we still confirm with you in the chat.",
    description: "From a first idea to a quote on WhatsApp: the steps of a custom crocheted animal order, and what we still confirm with you in the chat.",
    readTime: "3 min read",
    tag: "Custom orders",
    tags: ["Custom orders", "Ordering", "Studio"],
    cover: "handsGiraffe",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "A custom order starts with a rough idea. It ends with a quote you can accept or decline. Nothing is charged on the way. Here is what happens, in order." },
      { t: "h", text: "The steps" },
      { t: "ol", items: [
        "Open the Custom Studio and choose what you are making. You can change an animal we already make, work from a pet photo, or plan party favours.",
        "Say who it is for. It can be you, a gift, a group or a business.",
        "Choose an animal, a size and colours. The sizes are Small, Medium, Large and Extra large. If you cannot choose a size, ask the Studio to advise you.",
        "Add details and ideas if you like. This step is optional. You can add links, a short description, or shop animals you like.",
        "Tell us how many you need and the date you hope for. A date is a wish, not a booking.",
        "Leave your name and WhatsApp number. Check the summary and send. WhatsApp opens with your brief written out. You press send.",
      ] },
      i1,
      { t: "h", text: "What to have ready" },
      { t: "ul", items: [
        "A photo of the animal, the colours or the drawing you have in mind.",
        "A rough number of pieces.",
        "The date you hope for, if there is one.",
        "The name and WhatsApp number of an adult we can speak to.",
      ] },
      { t: "h", text: "After you press send" },
      { t: "p", text: "A person at Mikono reads your brief and replies in the chat. If you have photos, send them there. We may ask a few questions at once." },
      { t: "p", text: "Then we tell you what is possible and what it costs. Prices, delivery fees and timing are agreed in the chat. They are not on the website, because they depend on the piece." },
      i2,
      { t: "h", text: "Why the Studio shows no price" },
      { t: "p", text: "A new colour, a bigger size or an extra detail can change the work. A price shown in advance would be a guess. We prefer to give you one real figure." },
      { t: "h", text: "What can change" },
      { t: "p", text: "Some ideas must be changed to work in crochet. A very thin tail or a tiny detail may need to be simpler. We explain what and why before we start." },
      { t: "p", text: "The extras in the Studio are marked to be confirmed. A stitched word or an outfit is a question you ask us. It is not yet a promise." },
      i3,
      { t: "h", text: "Is custom right for you?" },
      { t: "p", text: "If a shop animal already looks right, order it from the shop. That is quicker. Choose custom when the colour, the animal or the reason is yours alone." },
      { t: "p", text: "Your draft stays on your own phone while you work. We do not save your phone number in it. You can stop and come back later." },
      { t: "p", text: "Big group orders and business orders are handled as quotes with a person. The wholesale and partners pages explain those routes." },
      { t: "h", text: "Three small examples" },
      { t: "ul", items: [
        "You want a grey elephant with a green scarf. Choose the elephant, a size and two colours.",
        "You want three matching animals for a family party. Choose party favours and give the number.",
        "You have a photo of your dog. Choose pet or character and tell us what matters most, like the ears or the colour.",
      ] },
      { t: "p", text: "In each case, we read your words and tell you what can be done. If we cannot make something, we say so and suggest a nearby choice." },
      { t: "p", text: "Start with one sentence about your idea. We will help with the rest." },
    ],
    cta: { text: "Not sure your idea can be crocheted? Describe it and we will tell you honestly.", message: "Hello Mikono Creations, I have an idea for a custom animal and would like to know if it is possible." },
    related: ["custom-brief-checklist", "corporate-gifts-custom-animals"],
    images: [
      { slot: "hero", after: null, brief: "A phone showing the Custom Studio summary screen next to a hand holding a crochet hook and yellow yarn.", altHint: "A phone with a brief on screen beside a hand holding a crochet hook." },
      { slot: "inline-1", after: "The steps", brief: "A pencil sketch of an animal on paper beside three yarn colour swatches.", altHint: "A sketch of an animal beside three coloured yarn swatches." },
      { slot: "inline-2", after: "After you press send", brief: "A phone with a WhatsApp chat open next to a crocheted giraffe, chat text blurred.", altHint: "A phone showing a chat beside a yellow crocheted giraffe." },
      { slot: "inline-3", after: "What can change", brief: "A small crocheted ear piece held between two fingers, close up, to show handwork.", altHint: "Fingers holding a small crocheted piece in yellow yarn." },
    ],
    sources: [],
    links: [
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Custom orders", href: "/custom" },
      { label: "Wholesale", href: "/wholesale" },
      { label: "Partners", href: "/partners" },
      { label: "Size finder", href: "/size-finder" },
    ],
  },

  {
    slug: "christmas-animals-choose-early",
    title: "Christmas animals: choose early, ask first",
    excerpt: "Planning a crocheted animal for Christmas: choose early, say who it is for, and let us confirm timing on WhatsApp before you rely on a date.",
    description: "Planning a crocheted animal for Christmas: choose early, say who it is for, and let us confirm timing on WhatsApp before you rely on a date.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Christmas", "Planning"],
    cover: "longTable",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "In Kenya, 25 December and 26 December are both public holidays. Many shops and services close. Each of our animals is crocheted by hand, one at a time. So it is wise to choose early and ask before you rely on a date." },
      { t: "h", text: "Four steps in order" },
      { t: "ol", items: [
        "Decide who it is for. Think about what that person likes. One favourite animal is better guidance than any rule from us.",
        "Pick an animal and a colour in the shop. A few animals are shown only in group photos. For those, we confirm the colour with you.",
        "Choose a size. The size finder shows Small, Medium, Large and Extra large in pictures. We have not published centimetres yet.",
        "Send your order list on WhatsApp. Say when you hope to have the gift. We reply with what is possible.",
      ] },
      i1,
      { t: "h", text: "What we cannot tell you here" },
      { t: "p", text: "We have not published lead times, delivery fees or last order dates for Christmas. They depend on the work in hand and on where the animal is going. We settle them with you in the chat." },
      { t: "p", text: "Nothing is charged until we have both agreed. If your date will not work, we say so at the start. Then you can choose something else." },
      { t: "h", text: "Gifts for many people" },
      { t: "p", text: "A family gathering often needs several gifts. The family builder lets you choose a group of safari animals. You set the sizes and colours and send one list." },
      { t: "p", text: "Three animals in matching colours can go to three cousins. Then nobody feels left out." },
      i2,
      { t: "p", text: "Add a gift note in the order form. If the animals are for different people, tell us in the chat so we keep the notes straight." },
      { t: "h", text: "If the person lives in another town" },
      { t: "p", text: "We work out delivery outside Nairobi case by case. Give us the town. Also give the name and phone number of the adult who will receive it. We will tell you what can be done." },
      { t: "p", text: "If you prefer to collect, the order form has a pickup choice." },
      { t: "h", text: "If you have no idea yet" },
      { t: "p", text: "The gift finder asks five quick questions. Then it suggests three animals from the shop. Your answers stay on your phone." },
      i3,
      { t: "p", text: "Use it as a nudge. If your own idea is stronger, follow that." },
      { t: "h", text: "A short timeline you can follow" },
      { t: "ul", items: [
        "Now: look at the shop and list the people you want to give to.",
        "Next: pick animals, colours and sizes, and send your list on WhatsApp.",
        "Then: answer our questions, agree the price and the delivery, and say how you will pay.",
        "Last: tell us the best day and place to hand over the gift.",
      ] },
      { t: "p", text: "You do not need a sack of presents. One animal chosen for one person is already a full gift." },
    ],
    cta: { text: "Know who the gift is for? Send us the animal, the size and the date you hope for.", message: "Hello Mikono Creations, I am planning a Christmas gift and would like to check what is possible." },
    related: ["choosing-a-size-as-a-gift", "baby-shower-gifts-from-nairobi"],
    images: [
      { slot: "hero", after: null, brief: "A medium crocheted lion wrapped loosely in plain brown paper and twine on a wooden table, soft window light.", altHint: "A crocheted lion partly wrapped in brown paper and tied with twine." },
      { slot: "inline-1", after: "Four steps in order", brief: "A phone showing the shop beside a notebook with a short gift list, text blurred.", altHint: "A phone and a notebook with a gift list on a table." },
      { slot: "inline-2", after: "Gifts for many people", brief: "Three matching cream animals in a row with three folded cards.", altHint: "Three cream crocheted animals in a row with three folded cards." },
      { slot: "inline-3", after: "If you have no idea yet", brief: "A hand holding a parcel in kraft paper at a doorway, face out of frame.", altHint: "A hand holding a paper-wrapped parcel at a door." },
    ],
    sources: ["https://en.wikipedia.org/wiki/Public_holidays_in_Kenya"],
    links: [
      { label: "Build a family", href: "/build-a-family" },
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Size finder", href: "/size-finder" },
      { label: "Gifts", href: "/gifts" },
      { label: "Lion", href: "/shop/lion" },
      { label: "Zebra", href: "/shop/zebra" },
    ],
  },

  {
    slug: "corporate-gifts-custom-animals",
    title: "Corporate gifts with a custom animal",
    excerpt: "A crocheted animal as a gift for staff or clients: what to decide first, what to put in the brief, and what we confirm on WhatsApp.",
    description: "A crocheted animal as a gift for staff or clients: what to decide first, what to put in the brief, and what we confirm on WhatsApp.",
    readTime: "3 min read",
    tag: "Business",
    tags: ["Business", "Corporate gifts", "Custom orders"],
    cover: "shelfReady",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "A company gift gets judged twice. First by the person who opens it. Then by anyone who wonders why you chose it. A crocheted animal made by hand in Nairobi gives you an easy answer to the second question." },
      { t: "h", text: "Decide five things first" },
      { t: "ul", items: [
        "How many people will get a gift. A rough number is fine.",
        "One design for all, or a few designs to choose from.",
        "Whether it should use your brand colours.",
        "The date the gifts must reach you.",
        "Where they go: one office, several, or straight to homes.",
      ] },
      { t: "p", text: "None of this has to be final. A rough answer is enough to start." },
      i1,
      { t: "h", text: "Plain, coloured or branded" },
      { t: "p", text: "The simplest choice is a shop animal in a colour that suits your company. The next step is a colour match. We try to follow your brand colours with the yarn we have." },
      { t: "p", text: "You can also ask for a stitched word or a mascot-style animal. We check those extras with you before we promise anything." },
      { t: "p", text: "In the Custom Studio, pick branded mascot, corporate gifts or hotels, lodges and shops. The Studio then asks the questions a business needs." },
      i2,
      { t: "h", text: "What happens next" },
      { t: "ol", items: [
        "You send the brief from the Studio. WhatsApp opens and you press send.",
        "We read it and ask for anything missing.",
        "We say what is possible and send a quote with prices and delivery.",
        "You decide. If you say yes, we agree how to pay in the chat.",
      ] },
      { t: "h", text: "Many pieces, one quote" },
      { t: "p", text: "Bigger orders are quoted by a person, so you will not find a price table on the site. If you also buy to resell, the wholesale page has a request for a price list." },
      { t: "p", text: "A person also handles invoices. Tell us what your finance team needs when you write." },
      i3,
      { t: "h", text: "A word on time" },
      { t: "p", text: "Each animal is crocheted one at a time. A large order needs planning. We have not published lead times. Give us your date early. We will tell you plainly if we can meet it." },
      { t: "h", text: "Questions to ask your team" },
      { t: "ul", items: [
        "Will people take the gift home, or keep it at work?",
        "Do we want the same animal for everyone, or a choice?",
        "Is there a colour our brand already uses?",
        "Who will receive the parcels, and when?",
      ] },
      { t: "p", text: "Answer these before you write. Your message will be clearer, and our reply will be faster." },
      { t: "p", text: "A gift on a desk for years says more than a gift that is put away in a week." },
    ],
    cta: { text: "Have a team, a date and a colour in mind? Start a business brief.", message: "Hello Mikono Creations, I would like to discuss corporate gifts. The approximate number of people is" },
    related: ["how-custom-orders-work", "custom-brief-checklist"],
    images: [
      { slot: "hero", after: null, brief: "A row of identical medium crocheted elephants in one calm colour on an office desk beside a laptop, no logos.", altHint: "A row of grey crocheted elephants on an office desk." },
      { slot: "inline-1", after: "Decide five things first", brief: "A notebook with a short checklist and a pen beside one crocheted animal, text blurred.", altHint: "A notebook and pen next to a crocheted animal." },
      { slot: "inline-2", after: "Plain, coloured or branded", brief: "Three yarn skeins in company-style colours beside a crocheted animal in the closest shade.", altHint: "Three skeins of yarn beside a crocheted animal in a matching colour." },
      { slot: "inline-3", after: "Many pieces, one quote", brief: "Animals packed upright in a cardboard box with paper between them, hands only.", altHint: "Crocheted animals packed upright in a cardboard box." },
    ],
    sources: [],
    links: [
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Wholesale", href: "/wholesale" },
      { label: "Partners", href: "/partners" },
      { label: "Elephant", href: "/shop/elephant" },
    ],
  },

  {
    slug: "easter-gifts-crocheted-animals",
    title: "Easter gifts with a crocheted animal",
    excerpt: "Easter moves every year. How to plan a crocheted animal gift around the long weekend, and why we confirm timing with you on WhatsApp.",
    description: "Easter moves every year. How to plan a crocheted animal gift around the long weekend, and why we confirm timing with you on WhatsApp.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Easter", "Planning"],
    cover: "zebrasBunnies",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Easter does not have a fixed date. It is the Sunday after the first full moon on or after 21 March. That puts it between 22 March and 25 April. Check a calendar for the year you are planning." },
      { t: "p", text: "In Kenya, Good Friday and Easter Monday are public holidays. So the weekend runs from Friday to Monday. Many families gather then. That is a good moment to hand over a small gift." },
      { t: "h", text: "Plan one: your own household" },
      { t: "p", text: "Many people link the rabbit with Easter. Our rabbits are brown with long ears. Some wear waistcoats. A small one can sit by a plate at the table or in a basket you already own." },
      i1,
      { t: "h", text: "Plan two: a host family" },
      { t: "p", text: "If you visit relatives, bring one animal for the whole house. Do not bring one for each person. A medium size is easy to carry and big enough to notice." },
      { t: "p", text: "Choose a calm colour. Wrap it in plain paper." },
      i2,
      { t: "h", text: "Plan three: a group" },
      { t: "p", text: "A church group, a school or a community event may want several animals. They could be raffle prizes or thank-you gifts. Tell us the number and the date on the partners page or in the Custom Studio. A person replies with what is possible." },
      { t: "h", text: "Order early" },
      { t: "p", text: "We crochet each animal by hand and we do not hold dates in advance. The sooner we hear from you, the sooner we can say yes or suggest another plan." },
      { t: "p", text: "We confirm price, delivery and timing on WhatsApp. Nothing is charged until you agree." },
      i3,
      { t: "h", text: "The note" },
      { t: "p", text: "You can add a gift note to the order. Use adult names only. Leave out a child's surname, school or age." },
      { t: "h", text: "Choosing a colour" },
      { t: "p", text: "Brown is the colour of our rabbits in the photos. Other animals come in grey, cream, yellow and tan. For a gift to a household, a soft colour is the easiest. For a gift to one person, pick the colour they already wear or love." },
      { t: "p", text: "If you are not sure, the gift finder asks a few questions and suggests three animals." },
      { t: "h", text: "What to send us" },
      { t: "ul", items: [
        "The animal and the colour you like, or a photo of one in the shop.",
        "The size: Small, Medium, Large or Extra large. Say if you are unsure.",
        "The town where the gift will go, or whether you will collect it.",
        "The day you hope to give it. We treat this as a wish until we confirm it.",
      ] },
      { t: "p", text: "That is enough for a first message. We write back on WhatsApp with questions, the price and a plan. You can still change your mind then." },
      { t: "p", text: "The long weekend gives the animal a few days to be admired before school and work begin again." },
    ],
    cta: { text: "Tell us your Easter date and who the gift is for.", message: "Hello Mikono Creations, I would like to give a crocheted animal at Easter. The date I have in mind is" },
    related: ["choosing-a-size-as-a-gift", "mothers-day-gift-ideas"],
    images: [
      { slot: "hero", after: null, brief: "A small brown crocheted rabbit in a plain woven basket on a cloth, spring daylight, no plastic grass.", altHint: "A brown crocheted rabbit in a woven basket." },
      { slot: "inline-1", after: "Plan one: your own household", brief: "A brown rabbit with a blue waistcoat on a dining table beside a plate.", altHint: "A crocheted rabbit in a blue waistcoat on a table beside a plate." },
      { slot: "inline-2", after: "Plan two: a host family", brief: "A medium animal wrapped in plain paper being handed over, hands only.", altHint: "Hands passing a paper-wrapped crocheted animal." },
      { slot: "inline-3", after: "Order early", brief: "A calendar page with a long weekend circled in pencil next to a small animal, numbers blurred.", altHint: "A paper calendar with a weekend circled beside a crocheted animal." },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Date_of_Easter",
      "https://en.wikipedia.org/wiki/Public_holidays_in_Kenya",
    ],
    links: [
      { label: "Rabbit", href: "/shop/rabbit" },
      { label: "Partners", href: "/partners" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Size finder", href: "/size-finder" },
    ],
  },

  {
    slug: "lodge-and-gift-shop-souvenirs",
    title: "Lodge and gift shop souvenirs in crochet",
    excerpt: "Choosing crocheted animals for a lodge or gift shop: species, sizes, colours and display, and how to start a wholesale request.",
    description: "Choosing crocheted animals for a lodge or gift shop: species, sizes, colours and display, and how to start a wholesale request.",
    readTime: "3 min read",
    tag: "Business",
    tags: ["Business", "Lodges", "Gift shops", "Wholesale"],
    cover: "tableOfAnimals",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Think of a guest on their last day. They pass reception, their room, the dining area and the shop. A souvenir must catch their eye in one of those places. It must also fit in a suitcase. Here is how to plan for that." },
      { t: "h", text: "At the shop shelf" },
      { t: "p", text: "Shelves sell by recognition. A guest who has just seen an elephant reaches for an elephant. Our safari range has elephants, giraffes, lions, rhinos, zebras, hippos and monkeys. Your shelf can match the animals your guests really see." },
      { t: "p", text: "In our own photos, animals are grouped by kind and carry hang tags. A mix of Small, Medium, Large and Extra large lets guests choose by budget and by suitcase space." },
      i1,
      { t: "h", text: "In the room" },
      { t: "p", text: "One animal on a bed or a chair works like a welcome. Think about the colours of your fabrics. Calm colours are usually easier to place than loud ones. We make animals in many colours." },
      i2,
      { t: "h", text: "At reception or the dining area" },
      { t: "p", text: "A larger animal near the door gets noticed. It also points guests to the shop. We can talk about display sizes separately from sizes for sale." },
      { t: "h", text: "What to tell us" },
      { t: "ul", items: [
        "The type of property or shop, and the town.",
        "The animals your guests ask about most.",
        "A rough mix of sizes.",
        "Colours that match your rooms or your packaging.",
        "Whether you expect to reorder, and how often.",
      ] },
      i3,
      { t: "h", text: "How to start" },
      { t: "p", text: "The wholesale page takes four kinds of request: a price list, a sample pack, a quote or a reorder. We reply on WhatsApp. We do not publish wholesale prices, minimum orders or lead times. A person gives you the real figures." },
      { t: "p", text: "Do you want your lodge colours or a branded tag? Open the Custom Studio and choose hotels, lodges and shops." },
      { t: "p", text: "The stockists page lists outlets near Nairobi that carry our animals. Visit one to see how a display looks before you plan yours." },
      { t: "h", text: "Small tips for display" },
      { t: "ul", items: [
        "Group animals by kind, so a guest sees all the lions together.",
        "Put the smallest size at the front, where a hand can reach it.",
        "Keep the animals off the floor and away from damp.",
        "Use one hang tag style across the shelf so it looks tidy.",
      ] },
      { t: "h", text: "A common question" },
      { t: "p", text: "Many owners ask, \"Do I have to pick one animal only?\" No. A first request can name several animals and sizes. Say which ones your guests ask about most." },
      { t: "p", text: "Then we reply on WhatsApp. We may suggest a smaller first selection, so you can see what sells before you add more. Prices and delivery are agreed there, and nothing is charged until you say yes." },
      { t: "p", text: "A tidy shelf of a few animals often does more than a crowded one." },
    ],
    cta: { text: "Tell us about your lodge or shop and we will suggest a first selection.", message: "Hello Mikono Creations, I run a lodge or shop and would like to ask about stocking your animals." },
    related: ["becoming-a-mikono-stockist", "why-wholesale"],
    images: [
      { slot: "hero", after: null, brief: "A small wooden shelf in a lodge gift shop with crocheted giraffes, elephants and lions in mixed sizes, warm light, no brand names.", altHint: "A shelf of crocheted giraffes, elephants and lions in a lodge shop." },
      { slot: "inline-1", after: "At the shop shelf", brief: "Hang tags on crocheted animals, close up, tags blank.", altHint: "Blank paper hang tags on crocheted animals." },
      { slot: "inline-2", after: "In the room", brief: "One medium giraffe on a neatly made bed with a folded throw.", altHint: "A yellow crocheted giraffe on a made bed." },
      { slot: "inline-3", after: "What to tell us", brief: "A shop counter with a notebook, a phone and two animals ready to be wrapped.", altHint: "A shop counter with a notebook, a phone and two crocheted animals." },
    ],
    sources: [],
    links: [
      { label: "Wholesale", href: "/wholesale" },
      { label: "Stockists", href: "/stockists" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Elephant", href: "/shop/elephant" },
      { label: "Giraffe", href: "/shop/giraffe" },
      { label: "Hippo", href: "/shop/hippo" },
      { label: "Safari animals", href: "/shop/safari-animals" },
    ],
  },

  {
    slug: "mothers-day-gift-ideas",
    title: "Mother's Day gifts: five kinds of mother",
    excerpt: "Mother's Day in Kenya falls on the second Sunday of May. Five gift ideas with a crocheted animal, sorted by the mother you have in mind.",
    description: "Mother's Day in Kenya falls on the second Sunday of May. Five gift ideas with a crocheted animal, sorted by the mother you have in mind.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Mother's Day"],
    cover: "giraffesSofa",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Kenyans mark Mother's Day on the second Sunday of May. It is not a public holiday. Many families start with church and share a meal. The gift comes somewhere in between. Here are five kinds of mother, and an animal for each." },
      { t: "h", text: "The mother who collects things" },
      { t: "p", text: "Her shelf tells a story. It may hold a shell, a wooden bowl and a photo. An animal can join it. Choose one with something to talk about, like a lion with a long yarn mane or a zebra with black and white stripes." },
      i1,
      { t: "h", text: "The mother with a calm house" },
      { t: "p", text: "Pick a quiet colour such as cream, grey or tan. Choose a medium size that sits on a bed or chair without taking over. A grey elephant has a steady look that suits that kind of home." },
      { t: "h", text: "The mother who wants nothing" },
      { t: "p", text: "She often means she does not want a fuss. A small animal in a paper bag is not a fuss. Write a few lines in the gift note. Let the note be the real present." },
      i2,
      { t: "h", text: "The grandmother" },
      { t: "p", text: "A bigger size gives her a lot to hold. Extra large is the biggest we make. Ask the family to share the cost and sign one card. Group gifts are easy to send on WhatsApp. We settle the price there." },
      { t: "h", text: "The mother far away" },
      { t: "p", text: "Maybe you live abroad and she lives in Kenya. You can order from where you are. We can arrange delivery to her, or to someone who will hand it over. We confirm the details with you on WhatsApp." },
      i3,
      { t: "h", text: "A word about the makers" },
      { t: "p", text: "Mikono supports 25+ women in Nairobi through this work. Each animal is crocheted by hand from recycled acrylic yarn. You can mention that when you give the gift." },
      { t: "h", text: "How to order, step by step" },
      { t: "ol", items: [
        "Pick the animal and the colour in the shop. Use the gift finder if you want help.",
        "Choose a size. The size finder shows Small, Medium, Large and Extra large side by side.",
        "Add a short gift note, then send your order list on WhatsApp.",
        "We reply with the price, the delivery plan and the timing. You say yes or no.",
      ] },
      { t: "p", text: "Start a few weeks before the second Sunday of May if you can. That gives us time to talk, and gives you time to change your mind." },
      { t: "h", text: "What to write on the card" },
      { t: "p", text: "Keep it short and true. Name one thing she did that you remember. Then add your name. A few real words mean more than a long poem." },
      { t: "p", text: "Think of what she would pick for herself. Then choose that animal." },
    ],
    cta: { text: "Tell us a little about her and we will suggest an animal.", message: "Hello Mikono Creations, I am looking for a Mother's Day gift. She likes" },
    related: ["gifts-for-family-in-kenya-from-abroad", "easter-gifts-crocheted-animals"],
    images: [
      { slot: "hero", after: null, brief: "A medium grey crocheted elephant on an armchair beside a folded kitenge cloth and a cup of tea, soft daylight, no people.", altHint: "A grey crocheted elephant on an armchair next to a kitenge cloth and a cup of tea." },
      { slot: "inline-1", after: "The mother who collects things", brief: "A shelf with a wooden bowl, a shell and a small crocheted lion.", altHint: "A shelf holding a wooden bowl, a shell and a crocheted lion." },
      { slot: "inline-2", after: "The mother who wants nothing", brief: "A small animal in a paper bag with a hand-written card, card text blurred.", altHint: "A small crocheted animal peeping out of a paper bag with a card." },
      { slot: "inline-3", after: "The mother far away", brief: "A phone on a table showing a chat, next to a wrapped parcel, chat text blurred.", altHint: "A phone with a chat open next to a wrapped parcel." },
    ],
    sources: [
      "https://nation.africa/kenya/news/kenyans-join-world-to-honour-mothers-1196732",
      "https://en.wikipedia.org/wiki/Mother%27s_Day",
    ],
    links: [
      { label: "Lion", href: "/shop/lion" },
      { label: "Zebra", href: "/shop/zebra" },
      { label: "Elephant", href: "/shop/elephant" },
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Size finder", href: "/size-finder" },
      { label: "Our makers", href: "/makers" },
    ],
  },

  {
    slug: "becoming-a-mikono-stockist",
    title: "Becoming a Mikono stockist: your questions",
    excerpt: "A shop owner's questions about stocking Mikono animals: what to send, what we reply with, and what we still confirm on WhatsApp.",
    description: "A shop owner's questions about stocking Mikono animals: what to send, what we reply with, and what we still confirm on WhatsApp.",
    readTime: "3 min read",
    tag: "Business",
    tags: ["Business", "Stockists", "Wholesale"],
    cover: "canopyStall",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Shop owners ask the same questions before a first order. Here they are with straight answers. Where an answer is still being confirmed, we say so." },
      { t: "h", text: "What do I send first?" },
      { t: "p", text: "Use the form on the wholesale page. Choose what you want: a price list, a sample pack, a quote or a reorder. Add your business name, your name and your WhatsApp number. Add what you sell and a rough quantity. A guess is fine." },
      i1,
      { t: "h", text: "What happens when I press send?" },
      { t: "p", text: "WhatsApp opens with your request written out. You press send. Someone at Mikono answers you there. The request starts a chat. It is not a promise to buy." },
      { t: "h", text: "Will I see prices on the site?" },
      { t: "p", text: "No. We do not publish wholesale prices. A person sends you the price list on WhatsApp. Then you can ask questions as you read it." },
      { t: "h", text: "Is there a minimum order? How long does an order take?" },
      { t: "p", text: "We have not published a minimum order or lead times. Ask in your first message. You will get the current answer." },
      i2,
      { t: "h", text: "Can I see the animals first?" },
      { t: "p", text: "Ask for a sample pack. It is an option on the form, so a small set can be arranged before a bigger order. We confirm what it holds and what it costs." },
      { t: "h", text: "Which animals sell best?" },
      { t: "p", text: "We do not publish sales figures and we will not guess. You can see what we make: safari animals, domestic animals such as rabbits, cats and dogs, and more animals such as octopuses, sharks and turtles. Start with the animals your own customers ask about." },
      { t: "h", text: "Can I have my own colours or a branded tag?" },
      { t: "p", text: "You can ask. Open the Custom Studio and choose hotels, lodges and shops, or branded mascot. We tell you if the request is possible before anything is made." },
      i3,
      { t: "h", text: "Where do shoppers find you now?" },
      { t: "p", text: "The stockists page lists outlets in and around Nairobi that carry our animals. Use it to see how shelves look. If you want your shop considered, say so in your first message." },
      { t: "h", text: "How should I set a first order?" },
      { t: "p", text: "Start with the animals your customers already know. Add a few sizes so people can pick by budget. Keep the first order small enough that you can watch it for a few weeks." },
      { t: "p", text: "Many shops start with a small first order and look at how the animals sit. Then they write again." },
    ],
    cta: { text: "Ready to ask? Start with the request that fits you best.", message: "Hello Mikono Creations, I own a shop and would like to ask about stocking your animals. My shop is in" },
    related: ["lodge-and-gift-shop-souvenirs", "why-wholesale"],
    images: [
      { slot: "hero", after: null, brief: "A shopkeeper's hands arranging crocheted giraffes and lions on a shelf, faces out of frame.", altHint: "Hands arranging crocheted giraffes and lions on a shop shelf." },
      { slot: "inline-1", after: "What do I send first?", brief: "A phone showing a form with a pen and a notebook beside it, text blurred.", altHint: "A phone with a form on screen, beside a pen and notebook." },
      { slot: "inline-2", after: "Is there a minimum order? How long does an order take?", brief: "A sample set of four small animals on kraft paper.", altHint: "Four small crocheted animals laid on kraft paper." },
      { slot: "inline-3", after: "Can I have my own colours or a branded tag?", brief: "A blank paper tag tied to a crocheted animal's arm, close up.", altHint: "A blank paper tag tied to a crocheted animal." },
    ],
    sources: [],
    links: [
      { label: "Wholesale", href: "/wholesale" },
      { label: "Stockists", href: "/stockists" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Partners", href: "/partners" },
      { label: "Safari animals", href: "/shop/safari-animals" },
      { label: "Domestic animals", href: "/shop/domestic-animals" },
      { label: "More animals", href: "/shop/more-animals" },
    ],
  },

  {
    slug: "eid-gifts-choosing-with-care",
    title: "Eid gifts: choosing with care",
    excerpt: "Eid al-Fitr follows the moon, so the date moves. A short guide to choosing a crocheted animal gift, asking first and ordering in good time.",
    description: "Eid al-Fitr follows the moon, so the date moves. A short guide to choosing a crocheted animal gift, asking first and ordering in good time.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Eid"],
    cover: "threeGiraffes",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Eid al-Fitr marks the end of Ramadan. It falls on the first day of Shawwal, the next month. The month starts when the new moon is seen. So the date can shift by a day. It also comes earlier in the calendar each year. In Kenya it is a public holiday." },
      { t: "p", text: "We do not speak for any community. This post is practical. It covers how to choose a gift, how to ask, and how to time an order." },
      { t: "h", text: "Ask first" },
      { t: "p", text: "Homes differ in what they like to receive. The people you visit know theirs best. If you are unsure, send a short message before you buy. It costs nothing and saves an awkward moment." },
      i1,
      { t: "h", text: "If the answer is yes" },
      { t: "ul", items: [
        "Choose a colour the household likes. Cream, tan, grey and soft green are easy to place.",
        "Choose a size by how you will give it. A small one is easy to carry on a visit. A large one makes a statement.",
        "Think of the whole household if you do not know everyone's taste.",
      ] },
      i2,
      { t: "h", text: "Timing when the date moves" },
      { t: "p", text: "The exact day is only sure close to the time. So plan for a few days, not one morning. Tell us the dates you can work with. We reply on WhatsApp with what is possible." },
      { t: "p", text: "We do not publish prices, delivery fees or timing on the site. You hear them from a person before you decide." },
      { t: "h", text: "Giving from a distance" },
      { t: "p", text: "If you cannot visit, the order form lets you ask us to arrange delivery to the person receiving the gift. Give the name and phone number of an adult. We confirm the details with you." },
      i3,
      { t: "h", text: "A greeting for the card" },
      { t: "p", text: "Eid Mubarak means blessed Eid. It is the usual greeting. Write it, then add your own name. A short note works best inside a WhatsApp message." },
      { t: "h", text: "Order early, then relax" },
      { t: "p", text: "Do not wait for the moon to be seen before you plan. Pick the animal and the size now. Send us your list and a range of dates. We can then tell you what is possible while you still have time to change your mind." },
      { t: "p", text: "If you want to give to many homes, use the family builder to make one list. Tell us which animal goes to which household." },
      { t: "p", text: "Asking first is how you learn what the family would like to receive." },
    ],
    cta: { text: "Tell us the colours you have in mind and the dates you can work with.", message: "Hello Mikono Creations, I would like to order a gift for Eid and would like to know what is possible. I need it around" },
    related: ["gifts-for-family-in-kenya-from-abroad", "choosing-a-size-as-a-gift"],
    images: [
      { slot: "hero", after: null, brief: "A medium cream crocheted giraffe beside a small bowl of dates on a plain tray, soft evening light, no people.", altHint: "A cream crocheted giraffe beside a bowl of dates on a tray." },
      { slot: "inline-1", after: "Ask first", brief: "A phone with a message being typed, held over a table, text blurred.", altHint: "A hand typing a message on a phone." },
      { slot: "inline-2", after: "If the answer is yes", brief: "Three colourways of one animal in cream, tan and soft green on a table.", altHint: "Three crocheted animals in cream, tan and soft green." },
      { slot: "inline-3", after: "Giving from a distance", brief: "A small gift bag with a card showing only a first name, the animal's head just above the bag.", altHint: "A gift bag with a card and a crocheted animal's head showing." },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Eid_al-Fitr",
      "https://en.wikipedia.org/wiki/Public_holidays_in_Kenya",
    ],
    links: [
      { label: "Giraffe", href: "/shop/giraffe" },
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Size finder", href: "/size-finder" },
      { label: "Gifts", href: "/gifts" },
    ],
  },

  {
    slug: "gifts-for-family-in-kenya-from-abroad",
    title: "Gifts for family in Kenya, sent from abroad",
    excerpt: "Living abroad and want to give to someone in Kenya? How to order, what to tell us, and what we confirm first.",
    description: "Living abroad and want to give to someone in Kenya? How to order, what to tell us, and what we confirm first.",
    readTime: "3 min read",
    tag: "Gifting",
    tags: ["Gifting", "Diaspora", "Ordering"],
    cover: "stallVisitors",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "You live in one country. The person you want to surprise lives in Kenya. You want something handmade to reach their hands. Here is how that works, with notes on what we still confirm." },
      { t: "h", text: "The idea" },
      { t: "p", text: "You order from wherever you are. The animal is delivered to a person in Kenya. The order form takes Kenyan delivery only. We have not confirmed sending parcels abroad." },
      { t: "h", text: "What you do" },
      { t: "ol", items: [
        "Choose the animal, colour and size in the shop. The gift finder can suggest three animals. The size finder helps with size.",
        "Add the animal to your order list and go to the order form.",
        "Choose delivery to someone else. Give the name and phone number of an adult who will receive it in Kenya.",
        "Write a gift note if you like. Use the names of adults only. Keep any details about children out of the note.",
        "Send the order on WhatsApp. A person replies when their workday starts.",
      ] },
      i1,
      { t: "h", text: "What we confirm with you" },
      { t: "ul", items: [
        "The price in Kenyan shillings.",
        "The delivery fee for the town it is going to.",
        "How you pay from abroad. We have not published payment methods yet.",
        "When it can reach the person, so a birthday is not missed.",
      ] },
      i2,
      { t: "h", text: "Choosing for someone you have not seen lately" },
      { t: "p", text: "Tastes change. Photos on a phone can be old. Start with colour. Grey, cream and tan suit most rooms." },
      { t: "p", text: "Then choose an animal that feels like home. A lion, a giraffe or an elephant carries a feeling of Kenya." },
      i3,
      { t: "h", text: "Small things that help" },
      { t: "p", text: "You can ask us if a photo of the finished animal can be sent to you before delivery. We do not promise it here, but it is a fair question." },
      { t: "p", text: "Keep the order reference that shows in your WhatsApp message. Tell the person you are giving to the animal and colour, so they know what to expect." },
      { t: "h", text: "A common question" },
      { t: "p", text: "People often ask, \"Can I pay in my own currency?\" We have not published payment methods, so we cannot promise that here. Ask in your first message. A person will tell you what works." },
      { t: "p", text: "Another common one is, \"What if the person is not home?\" Give us a second phone number if you have one. We agree a plan for the handover in the chat." },
      { t: "h", text: "A word about time zones" },
      { t: "p", text: "Your morning may be our evening. Send your message when you can and write down your time zone. We reply in our working hours. If you need the gift for a certain day, say so in the first message." },
      { t: "p", text: "A parcel from a relative far away arrives with extra meaning." },
    ],
    cta: { text: "Tell us who is receiving it and which town, and we will take it from there.", message: "Hello Mikono Creations, I live abroad and would like to send a gift to someone in Kenya. The town is" },
    related: ["mothers-day-gift-ideas", "christmas-animals-choose-early"],
    images: [
      { slot: "hero", after: null, brief: "A phone showing a chat beside a wrapped crocheted animal on a table, chat text blurred, no faces.", altHint: "A phone with a chat open beside a wrapped gift." },
      { slot: "inline-1", after: "What you do", brief: "A hand holding a phone over the order list screen, text blurred.", altHint: "A hand holding a phone showing an order list." },
      { slot: "inline-2", after: "What we confirm with you", brief: "A notebook with four ticked lines, text blurred, and a pen.", altHint: "A notebook with a short ticked list and a pen." },
      { slot: "inline-3", after: "Choosing for someone you have not seen lately", brief: "A crocheted lion and a crocheted giraffe side by side on a plain table.", altHint: "A crocheted lion beside a crocheted giraffe." },
    ],
    sources: [],
    links: [
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Size finder", href: "/size-finder" },
      { label: "Delivery", href: "/delivery" },
      { label: "Lion", href: "/shop/lion" },
      { label: "Giraffe", href: "/shop/giraffe" },
      { label: "Elephant", href: "/shop/elephant" },
    ],
  },

  {
    slug: "schools-and-ngos-working-with-mikono",
    title: "Schools and NGOs: working with Mikono",
    excerpt: "Ways a school, charity or community group might work with Mikono: event animals, sets for a room and animals made from your idea.",
    description: "Ways a school, charity or community group might work with Mikono: event animals, sets for a room and animals made from your idea.",
    readTime: "3 min read",
    tag: "Business",
    tags: ["Business", "Schools", "NGOs", "Partnerships"],
    cover: "courtyard",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Schools, charities and community groups write to us for different reasons. This post gives three ideas. They are examples, not a record of past projects. We settle every one with you in conversation." },
      { t: "h", text: "One: animals for an event" },
      { t: "p", text: "A fair, a prize-giving or a fundraiser may need animals that look good together. Tell us how many you need, the colours that suit your event and the date. We reply with what is possible and what it costs." },
      i1,
      { t: "h", text: "Two: a set for a room" },
      { t: "p", text: "A group may want a small set of animals to display or to use in storytelling. A set can be a safari family in matching colours." },
      { t: "p", text: "We make no claim about the age an animal suits. If you have a specific question, ask us and we will answer plainly." },
      i2,
      { t: "h", text: "Three: an animal from an idea" },
      { t: "p", text: "Some groups have a mascot, a set of colours or a drawing made by people in the community. The Custom Studio has a type for schools and projects. It has another for drawings." },
      { t: "p", text: "An adult sends the brief. We never ask for a child's name, age or school." },
      { t: "h", text: "How to start" },
      { t: "ul", items: [
        "Use the partners page for a school, an NGO or a brand.",
        "Use the wholesale page if you plan to buy a quantity from a price list.",
        "Use the Custom Studio if you want something made from your own idea.",
      ] },
      { t: "p", text: "Each one ends in a WhatsApp message that someone at Mikono reads and answers." },
      i3,
      { t: "h", text: "What we cannot say yet" },
      { t: "p", text: "We do not publish prices, minimum quantities or lead times. We do not show partner names or logos. We have not made safety, testing or age claims for our animals. We would rather say so than hide it." },
      { t: "p", text: "Here is what we can say. The plain animals are made in Nairobi from recycled acrylic yarn. Our plain animals contain zero plastic, and nothing on them comes off. They are easy to clean." },
      { t: "h", text: "What happens after you write" },
      { t: "ol", items: [
        "Someone at Mikono reads your message and replies on WhatsApp.",
        "We ask a few questions about the number, the colours and the date.",
        "We tell you what is possible, with the price and delivery plan.",
        "You decide. Nothing is charged until you agree.",
      ] },
      { t: "p", text: "If we cannot do something, we say so and suggest a nearby choice." },
      { t: "h", text: "What to put in your first message" },
      { t: "ul", items: [
        "Who you are and where you are.",
        "What the animals are for.",
        "How many you need, even as a guess.",
        "The date of your event, if there is one.",
      ] },
      { t: "p", text: "Look at the projects page before you write. Then tell us which one is closest to your idea." },
    ],
    cta: { text: "Tell us who your group is and what you have in mind.", message: "Hello Mikono Creations, I am writing for a school or organisation and would like to ask about" },
    related: ["corporate-gifts-custom-animals", "how-custom-orders-work"],
    images: [
      { slot: "hero", after: null, brief: "A table of crocheted safari animals set out for a school fair, with blank cards, adult hands only.", altHint: "Crocheted safari animals laid out on a fair table with blank cards." },
      { slot: "inline-1", after: "One: animals for an event", brief: "Animals in matching colours lined up on a trestle table with a cloth.", altHint: "A line of matching crocheted animals on a covered table." },
      { slot: "inline-2", after: "Two: a set for a room", brief: "A safari family of four animals on a low shelf in a bright room, no people.", altHint: "Four crocheted safari animals on a low shelf." },
      { slot: "inline-3", after: "Three: an animal from an idea", brief: "A generic unsigned drawing of an animal laid flat beside a crocheted version, no child visible.", altHint: "An animal drawing beside a crocheted animal made from it." },
    ],
    sources: [],
    links: [
      { label: "Partners", href: "/partners" },
      { label: "Wholesale", href: "/wholesale" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Projects", href: "/projects" },
      { label: "Zebra", href: "/shop/zebra" },
    ],
  },

  {
    slug: "choosing-a-size-as-a-gift",
    title: "Choosing a size when it is a gift",
    excerpt: "Small, Medium, Large or Extra large? Pick a size for a gift by how you will hand it over and where it will sit. No centimetres needed.",
    description: "Small, Medium, Large or Extra large? Pick a size for a gift by how you will hand it over and where it will sit. No centimetres needed.",
    readTime: "3 min read",
    tag: "Sizing",
    tags: ["Sizing", "Gifting"],
    cover: "ladder",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Choosing a size for yourself is easy. You know your own shelf. A gift is harder, because the space belongs to someone else. These rules start from how the gift is given. You do not need a tape measure." },
      { t: "h", text: "If you hand it over yourself" },
      { t: "p", text: "Think about carrying it. Small and Medium fit in a bag or on a lap in a matatu. Large and Extra large are an armful. That is fine if you drive or if the day is a big one." },
      i1,
      { t: "h", text: "If someone else delivers it" },
      { t: "p", text: "Then think about what the receiver does with it on the day. A larger animal is a moment, with a lot to unwrap. A smaller one slips into a bag and can be given quietly." },
      { t: "h", text: "If it will sit on a shelf or desk" },
      { t: "p", text: "Go smaller. Picture the animal beside a cup, a photo frame or a plant. If it would crowd the shelf, take the next size down." },
      i2,
      { t: "h", text: "If it will sit on a sofa or bed" },
      { t: "p", text: "Go larger. A Large or Extra large looks right on a sofa. A small one can get lost between the cushions." },
      { t: "h", text: "If you give a group" },
      { t: "ul", items: [
        "For matching animals, pick one size for everyone so nobody compares.",
        "For a family, pick neighbouring sizes, like the lions in a row.",
        "For a team, pick the size that fits the smallest desk.",
      ] },
      i3,
      { t: "h", text: "If you still cannot decide" },
      { t: "p", text: "Choose Medium. It is one step up from Small and one step down from Large. If the receiver would like another step, ask us on WhatsApp before anything is made." },
      { t: "p", text: "You can also describe the person, the place and the occasion to us. We will suggest a step. The size finder does the same with a few quick questions. The size guide shows the steps side by side." },
      { t: "p", text: "We have not published centimetre sizes yet, so every rule here uses comparisons. When we have measurements, they will go on the size guide first." },
      { t: "h", text: "A quick test at home" },
      { t: "p", text: "Find a cushion, a school bag or a cup in the place where the gift will sit. Hold your hands apart to show the size you imagine. Compare that with the lions in the row. The step that looks closest is your size." },
      { t: "p", text: "Pick the size that will look at home where it ends up." },
    ],
    cta: { text: "Describe the place and the person, and we will suggest a step.", message: "Hello Mikono Creations, can you help me choose a size for a gift? It will go to" },
    related: ["baby-shower-gifts-from-nairobi", "christmas-animals-choose-early"],
    images: [
      { slot: "hero", after: null, brief: "Four crocheted lions in a row from largest to smallest on a plain table, a gift bag beside them for scale.", altHint: "Four crocheted lions in a row from largest to smallest beside a gift bag." },
      { slot: "inline-1", after: "If you hand it over yourself", brief: "A medium animal sitting in an open tote bag, handles over the arm, face of the person out of frame.", altHint: "A crocheted animal sitting in a tote bag." },
      { slot: "inline-2", after: "If it will sit on a shelf or desk", brief: "A small animal on a desk beside a plant and a cup.", altHint: "A small crocheted animal on a desk beside a plant and a cup." },
      { slot: "inline-3", after: "If it will sit on a sofa or bed", brief: "A large animal on a sofa between two cushions.", altHint: "A large crocheted animal on a sofa between cushions." },
    ],
    sources: [],
    links: [
      { label: "Size finder", href: "/size-finder" },
      { label: "Size guide", href: "/size-guide" },
      { label: "Gift finder", href: "/gifts/finder" },
      { label: "Lion", href: "/shop/lion" },
      { label: "Gifts", href: "/gifts" },
    ],
  },

  {
    slug: "custom-brief-checklist",
    title: "What to put in a custom brief",
    excerpt: "A checklist for your custom animal brief: the details that help us answer quickly, with a weak and a strong example.",
    description: "A checklist for your custom animal brief: the details that help us answer quickly, with a weak and a strong example.",
    readTime: "3 min read",
    tag: "Custom orders",
    tags: ["Custom orders", "Checklist"],
    cover: "workroomPieces",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "A good brief saves a round of questions. You do not need to write well. You do not need to know crochet. Say what you see in your mind and add a few plain facts." },
      { t: "h", text: "The checklist" },
      { t: "ol", items: [
        "The animal, or the shop animal it is closest to.",
        "Size, from Small to Extra large. If you are unsure, say so.",
        "The colours, and where they go. For example, a grey body and a green tail.",
        "How many you need, as a rough number.",
        "The date you hope for, and whether it can move.",
        "Where it is going: pickup, a place in Nairobi or another town.",
        "Who we speak to. Give an adult's name and WhatsApp number.",
      ] },
      i1,
      { t: "h", text: "A brief that is too short" },
      { t: "p", text: "\"I would like a special animal for a friend.\"" },
      { t: "p", text: "That is kind. But we cannot send a quote. We do not know the animal, colour, size or date." },
      { t: "h", text: "A brief that helps" },
      { t: "p", text: "\"I would like an elephant in Medium, in slate blue, with cream ears. I need three, for three cousins, by the end of the month if that is possible. We are in Nairobi. Here is a photo of the colours I like.\"" },
      { t: "p", text: "We can answer this the same day. It names the animal, size, colours, number and place. It also asks a fair question about the date." },
      i2,
      { t: "h", text: "Photos, drawings and links" },
      { t: "p", text: "Send what you have. A pet photo, a colour picture, a drawing or a link all help. If a photo shows a child, crop it to the drawing or the animal. Leave out any child's name, school or age." },
      { t: "h", text: "What you can leave out" },
      { t: "ul", items: [
        "A budget, if you have none in mind. You can name a range or ask us to suggest one.",
        "Extras such as a stitched word, an outfit or packaging. They are marked to be confirmed, and you can raise them later.",
        "Technical words. Plain language works best.",
      ] },
      i3,
      { t: "h", text: "After the brief" },
      { t: "p", text: "A person replies and asks for anything missing. Then they tell you what is possible. Prices, delivery and timing come from them in the chat." },
      { t: "h", text: "If you have no photo" },
      { t: "p", text: "Use words. Say what the animal looks like and what it should feel like. You can point to a shop animal and say what you would change. For example, the lion, but with a cream mane." },
      { t: "p", text: "If your brief fits on one phone screen, it is usually enough." },
    ],
    cta: { text: "Have your list ready? Open the Studio and fill it in.", message: "Hello Mikono Creations, I have a brief for a custom animal. The animal, size and colours are" },
    related: ["how-custom-orders-work", "corporate-gifts-custom-animals"],
    images: [
      { slot: "hero", after: null, brief: "A notebook page with a handwritten checklist, text blurred, beside three yarn skeins in slate blue, cream and green.", altHint: "A notebook with a checklist beside three skeins of yarn." },
      { slot: "inline-1", after: "The checklist", brief: "A pen ticking a line on a printed checklist, close up, text blurred.", altHint: "A pen ticking a line on a checklist." },
      { slot: "inline-2", after: "A brief that helps", brief: "A phone photo of a colour swatch beside a small crocheted ear in the same colour.", altHint: "A coloured swatch beside a small crocheted ear in the same colour." },
      { slot: "inline-3", after: "What you can leave out", brief: "A flat lay of a skein of yarn, a hook and a paper tag.", altHint: "A skein of yarn, a crochet hook and a paper tag on a table." },
    ],
    sources: [],
    links: [
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Custom orders", href: "/custom" },
      { label: "Elephant", href: "/shop/elephant" },
      { label: "Size finder", href: "/size-finder" },
    ],
  },
];
