// Journal batch, part A: 12 new posts (6 on animals and wildlife of Kenya, 6 on parenting and play).
//
// TYPE NOTE: the existing `Post` type in ../journal.ts has different fields (excerpt, tag, cover as a PhotoId, no sources,
// no images). This file therefore defines a compatible local type, `BatchPost`, and re-uses the exported `Block` type.
// Mapping for the integration step: description -> excerpt, tags[0] -> tag, images[0] (hero) -> cover once a photo is attached.
//
// INTEGRATION NOTE: bodies contain {t: "image", slot: "inline-1" | "inline-2" | "inline-3"} blocks. The article renderer must
// handle the "image" block by looking up the matching entry in post.images (same slot), attaching the sourced photo and
// showing altHint as alt text. The hero is not a block: use images[0] (slot "hero"). Links are listed in post.links and cta.href
// and are also named in the text. Sources are plain URLs in post.sources.
//
// Rules followed: only approved Mikono claims (recycled acrylic yarn, zero plastic and nothing detachable on plain animals,
// easy to clean, made in Nairobi, 25+ women, founded 2019). No safety, age, test or developmental claims. No prices.
import type { Block } from "../journal/legacy";

export type ImageSlot = "hero" | "inline-1" | "inline-2" | "inline-3";

export type BatchBlock = Block | { t: "image"; slot: Exclude<ImageSlot, "hero"> };

export type BatchImage = {
  slot: ImageSlot;
  /** Heading text of the section this image follows. null for the hero. */
  after: string | null;
  brief: string;
  altHint: string;
};

export type BatchPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  tags: string[];
  pillar: "A" | "B";
  blocks: BatchBlock[];
  links: { label: string; href: string }[];
  cta: { text: string; message: string; href: string };
  images: BatchImage[];
  sources: string[];
};

export const partA: BatchPost[] = [
  {
    slug: "giraffe-questions-children-ask",
    title: "Giraffe questions children ask, answered",
    description: "Neck bones, favourite leaves and why the Maasai giraffe needs help. Plain answers for parents, plus a paper leaf game to play at home.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Animals of Kenya", "Giraffe"],
    pillar: "A",
    blocks: [
      { t: "p", text: "Children ask a lot of questions about giraffes. The neck always comes first. Here are the answers we give, in plain words, so you can share them at bedtime or on the way to the park." },
      { t: "h", text: "The tallest animal on land" },
      { t: "p", text: "The giraffe is the tallest mammal in the world. Its legs are long, and so is its neck. It can reach high into the branches of a tree." },
      { t: "p", text: "Show your child a picture of a giraffe. Ask them to point to the longest part. Most children point to the neck. Then ask about the legs, and let them look again." },
      { t: "h", text: "Seven bones in a long neck" },
      { t: "p", text: "A giraffe has seven bones in its neck. You have seven in yours. Touch the back of your own neck and you can feel them." },
      { t: "p", text: "The number is the same, but the size is not. Each bone in a giraffe's neck is very long. That is why the neck stretches so high." },
      { t: "p", text: "This is an easy fact for a child to keep. Say it together: seven bones, just like me." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What a giraffe eats" },
      { t: "p", text: "Giraffes eat leaves. They like acacia trees best. With a long neck, a giraffe reaches leaves that shorter animals cannot." },
      { t: "p", text: "A giraffe spends many hours of each day eating. It is careful about what it picks. Next time you walk past a tree, ask your child which leaves a giraffe could reach." },
      { t: "h", text: "Giraffes in Kenya" },
      { t: "p", text: "The Maasai giraffe lives mainly in Kenya and Tanzania. In 2019 the International Union for Conservation of Nature, or IUCN, listed it as Endangered. That word means the animal could disappear if nothing changes." },
      { t: "p", text: "The main causes are illegal hunting and the loss of land. Experts also say giraffes get less attention than elephants, rhinos and lions. Telling a child about giraffes is a small way to change that." },
      { t: "p", text: "You can keep it simple. Say that there are fewer giraffes than there used to be, and that people are working to protect them. Children do not need every number." },
      { t: "h", text: "Our crocheted giraffes" },
      { t: "p", text: "Our giraffes are crocheted by hand in Nairobi from recycled acrylic yarn. They have brown spots, two small horns and a round nose. The colours are yellow, cream, caramel tan and orange." },
      { t: "p", text: "Plain giraffes have zero plastic and nothing detachable. They are easy to clean. Please follow our care guide, and stay near when a young child plays." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "A reaching game for home" },
      { t: "p", text: "You need paper, tape and a giraffe. Keep both feet on the floor for the whole game." },
      { t: "ol", items: [
        "Cut out five paper leaves.",
        "Tape one leaf low on a wall, at your child's eye level.",
        "Tape a second leaf higher, at the top of your child's reach.",
        "Tape a third leaf higher still, out of reach.",
        "Hold the giraffe up to the highest leaf and say, this one is for the giraffe.",
      ] },
      { t: "p", text: "Let your child choose which leaf comes next. Then swap, so the giraffe goes first." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Choosing a size" },
      { t: "p", text: "A small giraffe fits on a shelf or in a bag. A large giraffe can sit beside a child on the sofa. If you cannot decide, the Size Finder asks a few questions and suggests a size." },
      { t: "p", text: "Then open the giraffe page and look at each colour in the photos. The pictures show what we have made." },
    ],
    links: [
      { label: "Giraffes in the shop", href: "/shop/giraffe" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Care guide", href: "/care" },
    ],
    cta: { text: "Ready to pick a giraffe? Start with the Size Finder.", message: "Hello Mikono Creations, I read your giraffe post and would like help choosing a giraffe.", href: "/size-finder" },
    images: [
      { slot: "hero", after: null, brief: "A crocheted yellow giraffe with brown spots standing on a wooden table in warm late afternoon light, plain wall behind it.", altHint: "A yellow crocheted giraffe with brown spots on a wooden table in warm light" },
      { slot: "inline-1", after: "Seven bones in a long neck", brief: "Close view of a real giraffe neck and head against sky, taken from below, no people in frame.", altHint: "A giraffe's long neck and head seen from below against the sky" },
      { slot: "inline-2", after: "Our crocheted giraffes", brief: "Hands working a crochet hook through yellow yarn beside finished giraffe pieces. Hands only.", altHint: "Hands crocheting with yellow yarn next to giraffe pieces" },
      { slot: "inline-3", after: "A reaching game for home", brief: "Paper leaves taped at different heights on a plain wall, a small crocheted giraffe on a chair beside them. No faces.", altHint: "Paper leaves taped at three heights on a wall with a crocheted giraffe on a chair" },
    ],
    sources: [
      "https://www.awf.org/wildlife-conservation/giraffe",
      "https://www.ecowatch.com/masai-giraffe-endangered-species-2639206101.html",
    ],
  },

  {
    slug: "pretend-play-ideas-with-crocheted-animals",
    title: "Pretend play ideas with crocheted animals",
    description: "Five simple games using animals you already have: a shop, a park ranger, a matatu ride, a school and a party. No special props needed.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Play at home", "Ideas"],
    pillar: "B",
    blocks: [
      { t: "p", text: "A basket of crocheted animals is a small stage. A child can turn it into a shop, a park or a bus in a minute. You only need to start the game. These ideas use things you already have at home." },
      { t: "h", text: "The animal shop" },
      { t: "p", text: "Spread a cloth on a table. Put the animals on it in rows. Your child is the shopkeeper and you are the buyer. Ask for a zebra, a lion or an elephant. Let the shopkeeper find it and hand it over." },
      { t: "p", text: "Use pretend coins, or none at all. After a few turns, swap places. You run the shop and your child does the buying." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Ranger and visitors" },
      { t: "p", text: "One person is the park ranger. The others are visitors in a car made from two chairs. Hide an animal behind a cushion. The ranger tells the visitors where to look: left of the sofa, near the door." },
      { t: "p", text: "A lion under a blanket makes a good first hide. A tall giraffe is easy to find, so give it to the youngest player." },
      { t: "h", text: "The matatu ride" },
      { t: "p", text: "Line up chairs in rows to make a matatu. The animals are the passengers. One child drives and another is the conductor. Call out stops you know, like the market or the school gate." },
      { t: "p", text: "Each passenger says where it is going. The elephant needs a whole seat to itself." },
      { t: "h", text: "Animal school" },
      { t: "p", text: "Sit the animals in a row facing a wall. Your child is the teacher. The rabbit forgot its homework. The cat is late again. Let your child write the story, and answer in the voice of the animal." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "An animal party" },
      { t: "p", text: "Plan a tea party on the floor. Each animal has a favourite food. A giraffe likes leaves and a hippo likes grass, so the menu is easy. Serve it on paper plates and let your child pour the pretend tea." },
      { t: "h", text: "Taking turns" },
      { t: "p", text: "Two children and one lion can cause trouble. Try a song. Sing one short verse. The first child holds the lion until the verse ends, then passes it on." },
      { t: "p", text: "If a turn ends in tears, put the lion in the basket and try again later. Not every game works every day." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "What to say while you play" },
      { t: "p", text: "Ask, what happens next? Then wait. The waiting is the hard part for adults. Your child will often have an answer if you give it a few seconds." },
      { t: "p", text: "You do not need a plot. Describe what you see: the zebra is by the door, the lion is asleep. Short lines are enough." },
      { t: "h", text: "Keep it simple" },
      { t: "p", text: "Start with two animals and one idea. Stop while the game is still fun. Play where you can see your child. On a plain animal there is zero plastic and nothing detachable, and you can clean it easily. Our care guide has the steps, and an adult should be close by during play." },
      { t: "p", text: "A set of four to six animals is plenty for all these games. Choose different sizes, so the shop has big and small stock. If the set is a present, the Gift Finder can help you choose." },
      { t: "p", text: "Voices cost nothing. Give the lion a deep one and see who laughs first." },
    ],
    links: [
      { label: "Lions", href: "/shop/lion" },
      { label: "Zebras", href: "/shop/zebra" },
      { label: "Elephants", href: "/shop/elephant" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Care guide", href: "/care" },
    ],
    cta: { text: "Choosing animals for a play set? Try the Gift Finder.", message: "Hello Mikono Creations, I would like help choosing a few animals for play.", href: "/gifts/finder" },
    images: [
      { slot: "hero", after: null, brief: "A small group of crocheted animals (lion, zebra, elephant) arranged on a play mat as if in a shop, soft daylight.", altHint: "Crocheted lion, zebra and elephant arranged on a mat like a shop display" },
      { slot: "inline-1", after: "The animal shop", brief: "A table with a patterned cloth and rows of crocheted animals, a hand reaching to pick one up. Hand only.", altHint: "A hand picking a crocheted animal from rows on a cloth-covered table" },
      { slot: "inline-2", after: "Animal school", brief: "Crocheted animals sitting in a row on a sofa facing a wall, as if in a classroom.", altHint: "A row of crocheted animals sitting on a sofa like pupils in a class" },
      { slot: "inline-3", after: "Taking turns", brief: "A single crocheted lion held in two adult hands over a rug, mane clearly visible. No faces.", altHint: "Two hands holding a crocheted lion over a rug" },
    ],
    sources: [
      "https://www.awf.org/wildlife-conservation/giraffe",
      "https://www.awf.org/wildlife-conservation/hippopotamus",
    ],
  },

  {
    slug: "elephant-facts-for-curious-children",
    title: "Elephant facts for curious children",
    description: "Six facts about the African elephant to read aloud, what Endangered means, and a herd game for the living room floor.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Animals of Kenya", "Elephant"],
    pillar: "A",
    blocks: [
      { t: "p", text: "Elephants are easy for children to love. They are huge, and they have a trunk. Here are six facts to read aloud, then a game, then a few words about our own elephants." },
      { t: "h", text: "Six facts to read aloud" },
      { t: "ol", items: [
        "The African elephant is the largest animal on land.",
        "The trunk does many jobs. An elephant breathes, smells, drinks and picks things up with it. It also uses it to make loud trumpet calls and to show affection.",
        "Tusks are very long front teeth. Elephants use them to look for food and water.",
        "Elephants live in family groups. An older female, called the matriarch, leads. Her female relatives of different ages stay with her.",
        "Grown males mostly live on their own.",
        "In one day an elephant eats a huge amount of plants and drinks many buckets of water.",
      ] },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Elephants in Kenya today" },
      { t: "p", text: "In 2021 the IUCN listed the African bush elephant as Endangered. This means there are fewer of them than there should be, and they could disappear if nothing changes." },
      { t: "p", text: "Elephants are hunted illegally for their ivory. People who do this are called poachers. In Kenya, rangers and conservation groups work in conservancies to protect elephants from them." },
      { t: "h", text: "How to talk about it with a child" },
      { t: "p", text: "Keep it short. Say that an Endangered animal is one with not many left, and that people are trying to help. Then stop and let your child ask questions." },
      { t: "p", text: "If you do not know an answer, say so. A library book, a ranger at a park or a conservation website are good places to check. We list our sources at the end of this page." },
      { t: "h", text: "Our elephants" },
      { t: "p", text: "Our elephants are crocheted by hand in Nairobi from recycled acrylic yarn. They have white tusks, big ears and a long trunk. The colours are grey, caramel brown, slate blue, lavender and dusty purple." },
      { t: "p", text: "A plain elephant has no plastic in it and no parts that come off. It is easy to clean too. Read the care guide before you wash anything, and keep watch while a young child plays." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "A herd walk game" },
      { t: "p", text: "This game turns a floor into a savanna. You need three or more animals and a blue cloth." },
      { t: "ul", items: [
        "Line up the animals. The biggest elephant is the matriarch, and she leads.",
        "Lay the blue cloth at the far end of the room. That is the water.",
        "Walk the herd across the floor, one animal at a time, to find the water.",
        "Stop for a rest in the shade under a table.",
      ] },
      { t: "p", text: "Let your child decide where the water is. If the herd gets lost, the matriarch chooses the next way. Then move the cloth and go again." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Picking a size" },
      { t: "p", text: "Elephants come in Small, Medium, Large and Extra large. A large elephant is big enough for a smaller animal to sit on its back. A small one fits in a bag. Think about where it will sit: a bed, a shelf or a bag." },
      { t: "p", text: "The Size Finder asks a few questions and gives you a size to start with. Pick a colour, pick a size, and let the matriarch lead the way." },
    ],
    links: [
      { label: "Elephants in the shop", href: "/shop/elephant" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Care guide", href: "/care" },
    ],
    cta: { text: "Want an elephant for the herd? Find your size first.", message: "Hello Mikono Creations, I read your elephant post and would like to ask about an elephant.", href: "/size-finder" },
    images: [
      { slot: "hero", after: null, brief: "A grey crocheted elephant with white tusks sitting on a green mat, side-on, soft window light.", altHint: "A grey crocheted elephant with white tusks on a green mat" },
      { slot: "inline-1", after: "Six facts to read aloud", brief: "An African elephant herd walking across open grassland in Kenya, an adult leading, no people in frame.", altHint: "A herd of African elephants walking across grassland" },
      { slot: "inline-2", after: "Our elephants", brief: "Several crocheted elephants in grey, slate blue and caramel brown lined up on a wooden table.", altHint: "Crocheted elephants in grey, slate blue and caramel brown on a table" },
      { slot: "inline-3", after: "A herd walk game", brief: "Crocheted animals lined up on a rug heading toward a blue cloth, shot low at floor level.", altHint: "Crocheted animals lined up on a rug walking toward a blue cloth" },
    ],
    sources: [
      "https://www.awf.org/wildlife-conservation/elephant",
    ],
  },

  {
    slug: "tidy-up-games-for-a-basket-of-animals",
    title: "Tidy-up games for a basket of animals",
    description: "Five short games that turn tidy-up time into play: animals go home, sort by colour, line up by size and more. Plus a few storage tips.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Play at home", "Routines"],
    pillar: "B",
    blocks: [
      { t: "p", text: "Tidy-up time is easier when it feels like a game. Children often ignore the word tidy. They answer to a game. Here are five that work with a basket of crocheted animals." },
      { t: "h", text: "Animals go home" },
      { t: "p", text: "Tell your child the basket is the animals' house. It is getting dark, and everyone must be inside before bedtime. Your child carries each animal in and says goodnight." },
      { t: "p", text: "Count them in. If one is missing, the search is part of the game. Check under the bed and behind the door." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Sort by colour" },
      { t: "p", text: "Ask for all the yellow animals first. Then grey, then brown. Your child collects each colour and places the group in the basket." },
      { t: "p", text: "Giraffes, elephants and lions give you plenty of colours to call out. If your animals are mixed, you can make up colours too: sunshine, mud, cloud." },
      { t: "h", text: "Smallest to biggest" },
      { t: "p", text: "Our animals come in Small, Medium, Large and Extra large. Put them in a line from the smallest to the biggest. Then carry them to the basket in that order, the biggest last." },
      { t: "p", text: "If you only have animals of the same size, line them up by something else. Ears, tails and manes work well." },
      { t: "h", text: "Closing the park" },
      { t: "p", text: "Play the ranger. The park closes at six. Everyone has to be back in the basket. Walk around the room with a pretend torch and check each corner." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "One song, one basket" },
      { t: "p", text: "Pick a song that lasts about a minute. Start it when tidy-up starts. When the song ends, the lid goes on. Use the same song every day so your child knows what it means." },
      { t: "p", text: "If the room is not finished when the song ends, sing it again. Keep the mood light. A game that turns into a fight is not a game." },
      { t: "h", text: "Where the basket lives" },
      { t: "p", text: "Choose a spot your child can reach. A low shelf or a corner of the room works well. A basket with air around the animals suits crochet better than a closed bag." },
      { t: "p", text: "Keep the basket away from damp walls and wet floors. If an animal gets dirty, wipe it early. The care guide has the steps we can share today." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "A small reminder" },
      { t: "p", text: "Mikono states zero plastic and nothing detachable for plain animals. Even so, keep an adult close when young children play, and look over each animal now and then. If you spot a problem, message us with a photo." },
      { t: "p", text: "A new rabbit or a small cat can be the one that leads the others to bed. Choose your next animal, or use the Size Finder to see what would fit your basket." },
    ],
    links: [
      { label: "Care guide", href: "/care" },
      { label: "Rabbits", href: "/shop/rabbit" },
      { label: "Cats", href: "/shop/cat" },
      { label: "Size Finder", href: "/size-finder" },
    ],
    cta: { text: "Want one more animal for the basket? Check sizes first.", message: "Hello Mikono Creations, I would like to add an animal to our basket. Can you help me choose a size?", href: "/size-finder" },
    images: [
      { slot: "hero", after: null, brief: "A woven basket on a bedroom floor filled with crocheted animals in mixed colours, with giraffe ears and a lion mane showing at the top.", altHint: "A woven basket on a floor full of crocheted animals" },
      { slot: "inline-1", after: "Animals go home", brief: "An adult hand lowering a crocheted giraffe into a basket, other animals already inside. Hand only.", altHint: "A hand placing a crocheted giraffe into a basket of animals" },
      { slot: "inline-2", after: "Closing the park", brief: "Crocheted animals lined up on a floor from smallest to largest, a torch beam across them.", altHint: "Crocheted animals lined up by size on a floor with a torch light" },
      { slot: "inline-3", after: "Where the basket lives", brief: "A low wooden shelf in a bedroom corner with an open basket of crocheted animals on it.", altHint: "A low wooden shelf with an open basket of crocheted animals" },
    ],
    sources: [],
  },

  {
    slug: "two-zebras-you-can-meet-in-kenya",
    title: "Two zebras you can meet in Kenya",
    description: "The plains zebra and the Grevy's zebra look alike, but they live in different places. How to tell them apart, and a spotting game for the car.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Animals of Kenya", "Zebra"],
    pillar: "A",
    blocks: [
      { t: "p", text: "Say zebra, and most people picture black and white stripes. Few people know there is more than one kind. Kenya has two of them. One is common. One is rare." },
      { t: "h", text: "The plains zebra" },
      { t: "p", text: "The plains zebra is the common one. It lives in grasslands and savannas across eastern and southern Africa. It is the zebra most visitors to Kenya see first." },
      { t: "p", text: "It eats many kinds of grass. Sometimes it also eats leaves and young trees. Each year, plains zebras in some places travel long distances in big groups, and they bring their young with them." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "The Grevy's zebra" },
      { t: "p", text: "The Grevy's zebra is rarer. Today it lives mainly in southern Ethiopia and northern Kenya, in dry grasslands where it can reach a steady supply of water. It is listed as Endangered." },
      { t: "p", text: "The African Wildlife Foundation says the stripes of a Grevy's zebra are as distinctive as human fingerprints. That is a good fact to share with a child who likes puzzles." },
      { t: "h", text: "How to tell them apart" },
      { t: "ul", items: [
        "A Grevy's zebra has larger ears than a plains zebra.",
        "Its stripes are narrower.",
        "A Grevy's zebra is bigger than a plains zebra.",
        "The plains zebra is found in many places. The Grevy's zebra is found in far fewer.",
      ] },
      { t: "p", text: "Ask your child to look at ears first. They are the easiest clue in a picture, because a pair of big, round ears stands out." },
      { t: "h", text: "Why a rare animal matters to a child" },
      { t: "p", text: "Children often care about the animal that is hard to find. Tell them that the Grevy's zebra is one of those, and that people in Kenya work to protect it. You do not need big numbers. One clear sentence is enough." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Our zebra" },
      { t: "p", text: "Our zebra is crocheted by hand in Nairobi from recycled acrylic yarn. It is black and white, with stripes worked into the yarn. A plain zebra has zero plastic and no loose parts, and you can wipe it clean." },
      { t: "p", text: "It comes in Small, Medium, Large and Extra large. We make one colourway today. If you would like to talk about an idea, send us a note through the Studio." },
      { t: "h", text: "A spotting game for the car" },
      { t: "p", text: "Stripes are easier to spot than most animals. Try this on a long drive or a matatu ride." },
      { t: "ol", items: [
        "Pick a colour and a pattern, like black and white stripes.",
        "Each time someone sees something with stripes, they call it out. A road crossing, a shirt or a fence all count.",
        "The first to reach ten wins the zebra title for the day.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "At home, line up your zebra beside other animals and ask which one has the boldest pattern. A zebra will win every time." },
    ],
    links: [
      { label: "Zebras in the shop", href: "/shop/zebra" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Size Finder", href: "/size-finder" },
    ],
    cta: { text: "Have an idea for a zebra of your own? Send it through the Studio.", message: "Hello Mikono Creations, I read your zebra post and have an idea I would like to share.", href: "/custom/studio" },
    images: [
      { slot: "hero", after: null, brief: "A black and white crocheted zebra standing on a wooden table outdoors, bright daylight, stripes clearly visible.", altHint: "A black and white striped crocheted zebra on a wooden table outdoors" },
      { slot: "inline-1", after: "The plains zebra", brief: "Plains zebras grazing on open grassland in Kenya, golden hour, no people.", altHint: "Plains zebras grazing on open grassland at golden hour" },
      { slot: "inline-2", after: "Why a rare animal matters to a child", brief: "A Grevy's zebra standing in dry northern Kenya grassland, big round ears and narrow stripes visible.", altHint: "A Grevy's zebra with large round ears standing in dry grassland" },
      { slot: "inline-3", after: "A spotting game for the car", brief: "A striped crocheted zebra on a car back seat beside a window with the road outside. No faces.", altHint: "A crocheted zebra sitting on a car seat by a window" },
    ],
    sources: [
      "https://www.awf.org/wildlife-conservation/zebra",
      "https://www.awf.org/wildlife-conservation/grevys-zebra",
    ],
  },

  {
    slug: "a-bedtime-safari-story-with-one-animal",
    title: "A bedtime safari story with one animal",
    description: "A short story you can read tonight, and four steps for making up your own with a crocheted animal. No props, no pressure.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Bedtime", "Storytelling"],
    pillar: "B",
    blocks: [
      { t: "p", text: "Some nights a book is too long, and some nights the book has run out. A story you make up with one animal can fill the gap. This post has a short story to read tonight and four steps to make your own." },
      { t: "p", text: "We do not promise any story will help a child sleep. Every child is different. But a quiet story gives the day a calm ending, and that is a good place to start." },
      { t: "h", text: "Tonight's story" },
      { t: "p", text: "Hold a crocheted elephant on your lap and read this slowly." },
      { t: "p", text: "The elephant was walking home. The sun was low and the grass was gold. She was tired, and her feet were slow." },
      { t: "p", text: "At the river she stopped for a drink. A small bird sat on a rock and said, you are late. I know, said the elephant. I stopped to watch the sunset." },
      { t: "p", text: "The bird laughed. Then it showed her the best place to sleep: a flat patch of warm sand by the water. The elephant lay down, one leg at a time." },
      { t: "p", text: "The river made its quiet sound. The grass did not move. The elephant closed her eyes. Goodnight, said the bird. Goodnight, said the elephant." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Four steps to make your own" },
      { t: "ol", items: [
        "Pick one animal. Hold it while you talk.",
        "Give it one small thing to do, like finding water or walking home.",
        "Add one other animal for it to meet, and one sentence they say to each other.",
        "End by lying down. The animal sleeps, and the story stops.",
      ] },
      { t: "p", text: "Keep the sentences short. Slow your voice down as you go. By the last line you should be nearly whispering." },
      { t: "h", text: "Let your child add one line" },
      { t: "p", text: "Pause and ask, what did the giraffe say? Let your child answer in a word or two. Then carry on. If they are too sleepy to speak, you can finish alone." },
      { t: "p", text: "Use the same opening each night, such as, the sun was low. A repeated line gives the story a familiar start." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Picking the animal" },
      { t: "ul", items: [
        "An elephant suits slow, heavy stories about walking and resting.",
        "A hippo suits stories about water and mud.",
        "A giraffe suits stories about looking down from a great height.",
        "A rabbit suits stories about small, quiet places.",
      ] },
      { t: "p", text: "For bedtime, we can only repeat what Mikono states: zero plastic and nothing detachable on plain animals, and easy to clean. Keep the care guide handy, and leave the animal where an adult can see it." },
      { t: "h", text: "A story animal by the bed" },
      { t: "p", text: "Some families keep one story animal on a shelf by the bed. It comes out at story time and goes back after. That way it stays special, and it is easy to find." },
      { t: "p", text: "A smaller size is easy to hold in one hand while you read. The Size Finder can help you choose. If you are buying for a friend, the Gift Finder can narrow down the options." },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Tonight, try the elephant. Tomorrow, let your child pick the animal. By the weekend, you may find they are the one telling the story." },
    ],
    links: [
      { label: "Elephants", href: "/shop/elephant" },
      { label: "Rabbits", href: "/shop/rabbit" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Care guide", href: "/care" },
    ],
    cta: { text: "Want a story animal for the shelf by the bed? Try the Size Finder.", message: "Hello Mikono Creations, I would like a story animal for bedtime. Can you help me choose a size?", href: "/size-finder" },
    images: [
      { slot: "hero", after: null, brief: "A crocheted elephant sitting on a folded blanket at the foot of a bed, lamp light, evening mood, no people.", altHint: "A crocheted elephant on a folded blanket at the foot of a bed" },
      { slot: "inline-1", after: "Tonight's story", brief: "A river in Kenya at sunset, flat warm sand by the water and a single rock, no animals needed.", altHint: "A river at sunset with warm sand and a rock on the bank" },
      { slot: "inline-2", after: "Let your child add one line", brief: "An adult hand holding a crocheted giraffe above a bedside table with a small lamp. Hand only.", altHint: "A hand holding a crocheted giraffe above a bedside table with a lamp" },
      { slot: "inline-3", after: "A story animal by the bed", brief: "A low shelf beside a bed with a crocheted rabbit and a picture book, soft evening light.", altHint: "A crocheted rabbit and a picture book on a low shelf by a bed" },
    ],
    sources: [],
  },

  {
    slug: "a-childs-guide-to-the-big-five",
    title: "A child's guide to the Big Five",
    description: "Lion, leopard, elephant, buffalo and rhino. One plain fact about each, what the name means, and which ones Mikono makes.",
    date: "2026-10-03",
    readTime: "4 min read",
    tags: ["Animals of Kenya", "Safari"],
    pillar: "A",
    blocks: [
      { t: "p", text: "Planning a safari? Your child will hear the words Big Five before you leave. Here is what they mean, and one fact about each animal that a child can remember." },
      { t: "h", text: "What the name means" },
      { t: "p", text: "The Big Five are the lion, the leopard, the elephant, the African buffalo and the rhino. The name was first used by hunters, who thought these five were the hardest to hunt on foot." },
      { t: "p", text: "Today people use the name in a kinder way. It is a checklist for visitors who want to see the five on safari. The Maasai Mara in Narok County is one reserve where all five can be seen." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Lion" },
      { t: "p", text: "Lions live in family groups called prides. Only the males grow a mane. Both males and females roar, and the sound travels far." },
      { t: "h", text: "Leopard" },
      { t: "p", text: "A leopard usually lives alone and is most active at night. It climbs well and can carry food up into a tree. Its spots are called rosettes, and they look a little like flowers." },
      { t: "h", text: "Elephant" },
      { t: "p", text: "The African elephant is the largest animal on land. A family group is led by an older female. The trunk is nose, hand and drinking straw in one." },
      { t: "h", text: "African buffalo" },
      { t: "p", text: "Buffalo live in herds. Both males and females have heavy, ridged horns. They have a good sense of smell, but weaker sight and hearing." },
      { t: "h", text: "Rhino" },
      { t: "p", text: "A rhino's horn is made of keratin, the same material as our hair and nails. The black rhino is listed as Critically Endangered. Kenya works hard to protect its black rhinos." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Which ones we make" },
      { t: "p", text: "We crochet three of the five: the lion, the elephant and the rhino. We do not make a leopard or a buffalo." },
      { t: "p", text: "Our lions are tan with a shaggy brown mane. Our elephants come in grey, caramel brown, slate blue, lavender and dusty purple. Our rhinos are light blue or brown with cream horns." },
      { t: "p", text: "All are crocheted by hand in Nairobi from recycled acrylic yarn. The plain ones carry zero plastic and nothing detachable. Cleaning is easy, and the care guide explains how. As always, an adult should stay near a young child at play." },
      { t: "h", text: "A safari checklist game" },
      { t: "p", text: "Make a card with five boxes, one for each animal. On a real safari, tick each one you spot. At home, use pictures or crocheted animals and tick them as you find them." },
      { t: "ul", items: [
        "Draw the five boxes and write one name next to each.",
        "Give a point for every animal seen, and a bonus for a mane or a horn.",
        "Say one fact about the animal before you tick the box.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Choosing a set" },
      { t: "p", text: "A set of three makes a good gift for a child who is going on safari. The Gift Finder can help you pick colours and sizes. If you need a different mix, tell us in the Studio." },
      { t: "p", text: "Two animals will be missing from the set, and that is fine. It leaves something for the child to look for in the park." },
    ],
    links: [
      { label: "Lions", href: "/shop/lion" },
      { label: "Elephants", href: "/shop/elephant" },
      { label: "Rhinos", href: "/shop/rhino" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Custom Studio", href: "/custom/studio" },
    ],
    cta: { text: "Packing for a safari? Let the Gift Finder suggest a set.", message: "Hello Mikono Creations, we are going on safari and I would like a set of animals as a gift.", href: "/gifts/finder" },
    images: [
      { slot: "hero", after: null, brief: "A crocheted lion, elephant and rhino standing in a row on a wooden table outdoors, soft daylight.", altHint: "A crocheted lion, elephant and rhino in a row on a wooden table" },
      { slot: "inline-1", after: "What the name means", brief: "Wide view of the Maasai Mara plains at golden hour with acacia trees, no people.", altHint: "Open plains with acacia trees at golden hour in the Maasai Mara" },
      { slot: "inline-2", after: "Rhino", brief: "A black rhino standing in grassland in Kenya, side view, horn clearly visible.", altHint: "A black rhino standing in grassland with its horn visible" },
      { slot: "inline-3", after: "A safari checklist game", brief: "A hand-drawn five-box checklist on paper beside a pencil and a crocheted lion.", altHint: "A hand-drawn checklist with five boxes beside a pencil and a crocheted lion" },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Big_Five_game",
      "https://en.wikipedia.org/wiki/Maasai_Mara",
      "https://www.awf.org/wildlife-conservation/lion",
      "https://www.awf.org/wildlife-conservation/leopard",
      "https://www.awf.org/wildlife-conservation/elephant",
      "https://www.awf.org/wildlife-conservation/african-buffalo",
      "https://www.awf.org/wildlife-conservation/rhino",
      "https://www.wwf.org.uk/press-release/kenya-black-rhino-reach-milestone",
    ],
  },

  {
    slug: "a-welcome-gift-for-a-new-brother-or-sister",
    title: "A welcome gift for a new brother or sister",
    description: "A new baby changes the house. Here is a simple idea for two gifts, one for the baby and one for the older child, and how to pick sizes.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Gifts", "Family"],
    pillar: "B",
    blocks: [
      { t: "p", text: "When a new baby arrives, visitors bring gifts for the baby. The older child often gets nothing. This post is about a small change: bring two gifts, and make one of them for the big brother or sister." },
      { t: "h", text: "Why two gifts" },
      { t: "p", text: "An older child may feel left out when the house fills with baby things. A gift of their own says, you matter too. It does not need to be big or loud." },
      { t: "p", text: "A crocheted animal makes an easy choice. It can sit on a bed, ride in a bag and join the games your child already plays." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "The gift for the older child" },
      { t: "p", text: "Pick an animal your child already likes. A large one can be a good choice, since it looks important. Give it with a short line, such as, you are the big sister now, and this is your helper." },
      { t: "p", text: "Let your child hold the animal while you talk. Do not push a big speech. A hug and a name for the animal go a long way." },
      { t: "h", text: "The gift for the baby" },
      { t: "p", text: "Here we want to be careful. We make no age or safety claims for our animals, so we cannot tell you what suits a newborn. What we state is short. Plain animals are made of recycled acrylic yarn with zero plastic and nothing detachable, and they are easy to clean." },
      { t: "p", text: "If the baby is very small, you might give the animal to the parents as a keepsake for later. They can decide when and how it is used. Adult supervision is needed at all times, and the care guide has our cleaning notes." },
      { t: "h", text: "A matching pair" },
      { t: "p", text: "Some families like the idea of a pair: a big elephant for the older child and a small one for the baby. The two look like they belong together, even in different sizes." },
      { t: "ul", items: [
        "Elephant: one large and one small, in the same colour.",
        "Bear: one tan, one blue, so each child has a colour.",
        "Hippo: a quiet choice for a child who likes water games.",
      ] },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Choosing the sizes" },
      { t: "p", text: "We make Small, Medium, Large and Extra large. A sibling gift often works well as one Large and one Small. The Size Finder asks about the person and the place, then suggests a size. Try it with the older child in mind first." },
      { t: "h", text: "Writing the gift note" },
      { t: "p", text: "If you add a note, keep it short and kind. Use first names only. Please do not include a child's surname or school in the note." },
      { t: "p", text: "Here is one that works: Welcome to the family, little one. This is for you, big brother, from someone who thinks you are brilliant." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "If you want something different" },
      { t: "p", text: "The Gift Finder lists ideas by occasion. If you have a colour in mind, or a name you want to match with an animal, the Studio lets you send us the idea. We will tell you what is possible." },
      { t: "p", text: "A baby will not remember who gave which gift. The big sister will." },
    ],
    links: [
      { label: "Elephants", href: "/shop/elephant" },
      { label: "Bears", href: "/shop/bear" },
      { label: "Hippos", href: "/shop/hippo" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Custom Studio", href: "/custom/studio" },
    ],
    cta: { text: "Choosing for a new family? Start with the Gift Finder.", message: "Hello Mikono Creations, I would like two gifts for a new baby and the older child. Can you help?", href: "/gifts/finder" },
    images: [
      { slot: "hero", after: null, brief: "Two crocheted elephants in the same colour, one large and one small, sitting side by side on a bed with a plain wrapping cloth.", altHint: "A large and a small crocheted elephant side by side on a bed" },
      { slot: "inline-1", after: "Why two gifts", brief: "A gift wrapped in kitenge-style cloth lying on a bed beside a handwritten tag. No people.", altHint: "A gift wrapped in patterned cloth on a bed with a handwritten tag" },
      { slot: "inline-2", after: "A matching pair", brief: "A tan and a blue crocheted bear sitting together on a grey sofa.", altHint: "A tan crocheted bear and a blue crocheted bear on a grey sofa" },
      { slot: "inline-3", after: "Writing the gift note", brief: "A hand writing a short note on a card next to a wrapped parcel. Hand only.", altHint: "A hand writing a note on a card beside a wrapped parcel" },
    ],
    sources: [],
  },

  {
    slug: "a-hippos-day-and-night",
    title: "A hippo's day and night, in plain words",
    description: "Hippos spend the day in water and come out to graze after dark. A simple timeline of a hippo's day, with a floor game for children.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Animals of Kenya", "Hippo"],
    pillar: "A",
    blocks: [
      { t: "p", text: "A hippo has two lives. One happens by day in the water. The other happens at night on land. If you want a child to remember a hippo, tell the day and the night as two parts of one story." },
      { t: "h", text: "Daytime: in the water" },
      { t: "p", text: "Hippos spend most of the daylight hours in rivers, lakes or mud. The water keeps their skin moist and stops the sun from drying it." },
      { t: "p", text: "A hippo's skin looks thick, but it is delicate and can burn. The animal makes an oily, reddish liquid that helps protect it from the sun and from infection." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Evening: time to get out" },
      { t: "p", text: "When the light fades, hippos leave the water. They walk to nearby grassland to feed." },
      { t: "h", text: "Night: grazing" },
      { t: "p", text: "A hippo eats grass during the night. It may feed for several hours and walk a good distance from the water." },
      { t: "p", text: "Hippos live in groups. A territorial male looks after the stretch of water they share." },
      { t: "h", text: "What the name means" },
      { t: "p", text: "The word hippopotamus comes from ancient Greek. It means river horse. A hippo is not a horse, but you can see why people chose the name." },
      { t: "h", text: "A hippo in Kenya today" },
      { t: "p", text: "The IUCN lists the hippo as Vulnerable. That means its numbers are going down and it needs care. You can tell a child that hippos need clean rivers and safe grassland to live." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Our hippo" },
      { t: "p", text: "Our hippo is crocheted by hand in Nairobi from recycled acrylic yarn. In our photo it is navy, with ringed eyes and a magenta dress with a multicoloured hem." },
      { t: "p", text: "A hippo in a dress is not a plain animal. Our zero plastic and nothing detachable statement covers plain animals only. We have not confirmed it for animals with clothes, so ask us if you want to know more." },
      { t: "h", text: "A day and night game" },
      { t: "p", text: "You need a hippo, a blue cloth and a green cloth. Put the blue cloth on one side of the room and the green cloth on the other." },
      { t: "ol", items: [
        "It is morning. The hippo sits on the blue cloth. It is in the river.",
        "Say, the sun is high. The hippo stays where it is.",
        "Say, the sun is going down. The hippo walks across the floor.",
        "The hippo lands on the green cloth and starts to graze.",
        "Say, the sun is coming up. The hippo walks back to the river.",
      ] },
      { t: "p", text: "Switch the light on and off, or draw the curtain, for day and night. Let your child say the lines after a few rounds." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "A small note on hippos in real life" },
      { t: "p", text: "A hippo may look slow and round, but it has a very strong bite. If you visit one in a park, listen to your guide and keep your distance." },
      { t: "p", text: "Ask your child to look for the hippo's eyes and nose first, because they sit high on its head." },
    ],
    links: [
      { label: "Hippo in the shop", href: "/shop/hippo" },
      { label: "Size Finder", href: "/size-finder" },
    ],
    cta: { text: "Want to see the hippo more closely? Open its page.", message: "Hello Mikono Creations, I read your hippo post and would like to ask about the hippo.", href: "/shop/hippo" },
    images: [
      { slot: "hero", after: null, brief: "A navy crocheted hippo with a magenta dress held up in one hand against a plain wall. Hand only, no face.", altHint: "A navy crocheted hippo in a magenta dress held in a hand" },
      { slot: "inline-1", after: "Daytime: in the water", brief: "A group of hippos resting in a river in Kenya, only heads and backs above the water, midday light.", altHint: "Hippos resting in a river with only their heads and backs above the water" },
      { slot: "inline-2", after: "A hippo in Kenya today", brief: "A calm river bend with grassy banks in late afternoon, no animals in frame.", altHint: "A calm river bend with grassy banks in late afternoon light" },
      { slot: "inline-3", after: "A day and night game", brief: "A blue cloth on one side of a rug and a green cloth on the other, a crocheted hippo in the middle.", altHint: "A crocheted hippo between a blue cloth and a green cloth on a rug" },
    ],
    sources: [
      "https://www.nationalgeographic.com/animals/mammals/facts/hippopotamus",
      "https://www.awf.org/wildlife-conservation/hippopotamus",
    ],
  },

  {
    slug: "taking-an-animal-to-school-a-short-checklist",
    title: "Taking an animal to school: a short checklist",
    description: "Before a crocheted animal goes in the school bag, check a few small things. A simple list for parents, from asking the teacher to wiping it clean.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["School", "Parents"],
    pillar: "B",
    blocks: [
      { t: "p", text: "Many children want to bring a favourite animal to school. Some schools allow it and some do not. A little planning keeps the day calm for you, your child and the teacher." },
      { t: "h", text: "Ask the school first" },
      { t: "p", text: "Check the school's rules before the animal goes in the bag. Some schools allow small items, and some ask children to leave them at home. If you are not sure, send a short message to the teacher." },
      { t: "p", text: "Ask two things. Is it allowed? And where should it stay during lessons? The answers will save a lot of tears." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Choose a small one" },
      { t: "p", text: "A small animal fits in a bag pocket and does not take up desk space. We make four sizes: Small, Medium, Large and Extra large. S is the smallest size of each animal. The Size Finder can help you choose one that fits a school bag." },
      { t: "p", text: "A dog or a bear in Small is a common pick. Check the animal beside the bag at home first." },
      { t: "h", text: "Pick the pocket" },
      { t: "p", text: "Show your child where the animal lives in the bag. Use an outside pocket that is easy to reach, or a front pocket with a zip. Tell them to keep it there until home time." },
      { t: "h", text: "Plan for lost things" },
      { t: "p", text: "Things go missing at school. Talk to your child before it happens. Say what to do if the animal is lost: tell the teacher, and then tell you. Say it is not a big problem. You can find it, or you can talk about a new one." },
      { t: "p", text: "Do not write a child's surname or school name on the animal. A first name on a small tag inside the bag is enough." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "The home time routine" },
      { t: "p", text: "Decide what happens to the animal when your child gets home. It could go on the bed, in the basket or on a shelf. A fixed spot makes the day easier to end." },
      { t: "ul", items: [
        "Take it out of the bag at the door.",
        "Check it for dust, damp or loose yarn.",
        "Put it in its place before snacks.",
      ] },
      { t: "h", text: "Cleaning" },
      { t: "p", text: "School bags are not always clean. Mikono animals are easy to clean, and the care guide has gentle steps. Wipe marks early, before they set." },
      { t: "p", text: "A plain animal has zero plastic and nothing detachable. Still, it helps to look it over now and then, and an adult should watch young children at play." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "If the school says no" },
      { t: "p", text: "Do not argue. Pick another place for the animal, like the car, the bedside table or the gate at home time. Your child can say goodbye in the morning and hello in the afternoon." },
      { t: "p", text: "For an animal that stays home, a larger size works well. For one that travels, choose Small." },
    ],
    links: [
      { label: "Dogs", href: "/shop/dog" },
      { label: "Bears", href: "/shop/bear" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Care guide", href: "/care" },
    ],
    cta: { text: "Need a small one for a school bag? Use the Size Finder.", message: "Hello Mikono Creations, I would like a small animal that fits in a school bag. Can you help me choose?", href: "/size-finder" },
    images: [
      { slot: "hero", after: null, brief: "A school bag on a chair with a small crocheted dog sitting in the open front pocket, morning light. No people.", altHint: "A school bag with a small crocheted dog in the front pocket" },
      { slot: "inline-1", after: "Ask the school first", brief: "A hand typing a short message on a phone beside a school exercise book. Hand only.", altHint: "A hand typing a message on a phone beside an exercise book" },
      { slot: "inline-2", after: "Plan for lost things", brief: "A small white tag with a first name written on it, clipped inside a school bag.", altHint: "A small name tag clipped inside a school bag" },
      { slot: "inline-3", after: "Cleaning", brief: "A hand wiping a crocheted bear gently with a damp cloth on a towel. Hand only.", altHint: "A hand gently wiping a crocheted bear with a damp cloth" },
    ],
    sources: [],
  },

  {
    slug: "rhinos-in-kenya-what-children-can-learn",
    title: "Rhinos in Kenya: what children can learn",
    description: "Two kinds of rhino live in Africa. Kenya cares for black rhinos, and their numbers are growing. Plain facts about horns, lips and hope.",
    date: "2026-10-03",
    readTime: "3 min read",
    tags: ["Animals of Kenya", "Rhino"],
    pillar: "A",
    blocks: [
      { t: "p", text: "Rhinos are heavy, quiet and easy to miss in the bush. They are also one of Kenya's biggest conservation stories. This post gives you a few plain facts and a good ending." },
      { t: "h", text: "Two kinds in Africa" },
      { t: "p", text: "Africa has two kinds of rhino: the black rhino and the white rhino. Both have two horns. Kenya is known for protecting black rhinos." },
      { t: "p", text: "Their colour is not the main difference. Their mouths are. The black rhino has a pointed upper lip, shaped a bit like a triangle. It uses the point to grab leaves, buds and shoots from bushes and trees." },
      { t: "p", text: "The white rhino eats grass on open savanna instead. Ask your child to guess which one has the pointed lip. Then look at pictures together." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What a horn is made of" },
      { t: "p", text: "A rhino's horn is made of keratin. Keratin is also what your hair and nails are made of. A horn is not bone and does not have special powers." },
      { t: "p", text: "That is worth saying out loud to a child. Some people hunt rhinos for their horns because of false beliefs. The horn does the same job on a rhino as a nail does on a finger." },
      { t: "h", text: "Black rhinos in Kenya" },
      { t: "p", text: "The black rhino is listed as Critically Endangered. That is a very high risk of disappearing. In the 1980s Kenya had fewer than 400 of them." },
      { t: "p", text: "Today the Kenya Wildlife Service says there are more than 1,000. That is a big gain, and it came from years of work by rangers, sanctuaries and conservation groups. WWF reports that Kenya aims for 2,000 black rhinos by 2037." },
      { t: "p", text: "It is a good story to tell a child. It shows that careful work can help an animal in trouble." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Our rhinos" },
      { t: "p", text: "Our rhinos are crocheted by hand in Nairobi from recycled acrylic yarn. They are light blue or brown, with cream horns." },
      { t: "p", text: "Rhinos that are plain, with no clothes or extras, have zero plastic and nothing detachable. You can clean them easily by following the care guide. Stay close when a young child plays." },
      { t: "h", text: "A talking game" },
      { t: "p", text: "Put a rhino and an elephant side by side. Ask your child to describe how they differ, in as many ways as they can." },
      { t: "ul", items: [
        "One has a trunk and one has horns.",
        "One has big ears and one has small ears.",
        "One has tusks and one has a horn made of keratin.",
      ] },
      { t: "p", text: "Count the answers together. There is no wrong total. The point is to look closely and say what you see." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "A gift for a rhino fan" },
      { t: "p", text: "If a child in your family loves rhinos, a crocheted rhino is a simple gift. The Gift Finder asks a few questions and suggests animals by occasion. The Size Finder helps with the size." },
      { t: "p", text: "From fewer than 400 to more than 1,000 in a few decades is a number a child can say aloud with pride." },
    ],
    links: [
      { label: "Rhinos in the shop", href: "/shop/rhino" },
      { label: "Elephants", href: "/shop/elephant" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Size Finder", href: "/size-finder" },
    ],
    cta: { text: "Know a rhino fan? Let the Gift Finder help you pick.", message: "Hello Mikono Creations, I am looking for a rhino as a gift. Can you help?", href: "/gifts/finder" },
    images: [
      { slot: "hero", after: null, brief: "A light blue crocheted rhino with cream horns on a table, side view, outdoor light.", altHint: "A light blue crocheted rhino with cream horns on a table" },
      { slot: "inline-1", after: "Two kinds in Africa", brief: "Close side view of a black rhino browsing a bush in Kenya, pointed upper lip visible.", altHint: "A black rhino browsing a bush with its pointed upper lip" },
      { slot: "inline-2", after: "Black rhinos in Kenya", brief: "A wide Kenyan conservancy landscape with grass and distant hills, a ranger vehicle small in the distance. No close faces.", altHint: "A Kenyan conservancy landscape with grassland and hills" },
      { slot: "inline-3", after: "A talking game", brief: "A crocheted rhino and a crocheted elephant side by side on a rug.", altHint: "A crocheted rhino and a crocheted elephant side by side on a rug" },
    ],
    sources: [
      "https://www.awf.org/wildlife-conservation/rhino",
      "https://www.wwf.org.uk/press-release/kenya-black-rhino-reach-milestone",
    ],
  },

  {
    slug: "gift-ideas-by-occasion-with-crocheted-animals",
    title: "Gift ideas by occasion, plain and simple",
    description: "A birthday, a new baby, a thank-you, a goodbye. Which crocheted animal fits which occasion, how to pick a size and how to add a note.",
    date: "2026-10-03",
    readTime: "4 min read",
    tags: ["Gifts", "Ideas"],
    pillar: "B",
    blocks: [
      { t: "p", text: "Choosing a gift for a child is easier when you start with the occasion. Here are six, with one animal idea for each. Use them as a start and change what does not fit." },
      { t: "h", text: "A birthday" },
      { t: "p", text: "For a birthday, pick the animal the child already talks about. If it is lions, buy a lion. A child who gets what they asked for feels heard." },
      { t: "p", text: "A medium or large size feels like a proper present. A giraffe is easy to spot when the wrapping comes off." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "A new baby in the family" },
      { t: "p", text: "For a baby, think about the parents as the ones you are giving to. We make no age or safety claims, so we do not say what suits a newborn. Our statement is limited to materials and cleaning, and it covers plain animals only." },
      { t: "p", text: "A note that says, for when baby is ready, lets the parents decide. Remember a gift for the older sibling too." },
      { t: "h", text: "A visit to someone's home" },
      { t: "p", text: "Going to a house with children? A small animal is easy to carry and easy to wrap. A rabbit, a cat or a small turtle will fit in a bag." },
      { t: "p", text: "A gift that fits in your hand never feels like too much." },
      { t: "h", text: "A thank-you" },
      { t: "p", text: "Say thank you to a teacher or neighbour with something from the family. A butterfly in a colour that suits them is a light choice. A short note makes it personal." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "A goodbye" },
      { t: "p", text: "When a friend is moving away, an animal can sit on a shelf in the new room. Pick a small one that travels well. Add a note with your name and the date." },
      { t: "p", text: "For Kenyan families living abroad, ask us about sending a gift to someone in Kenya. Delivery details are confirmed on WhatsApp." },
      { t: "h", text: "A big change" },
      { t: "p", text: "A new school, a new house or a long trip can be a lot for a child. An animal can come along as company. We cannot promise it will make a change easier, but many parents like to give one at these times." },
      { t: "h", text: "Choosing a size" },
      { t: "ul", items: [
        "Small fits a hand, a pocket or a school bag.",
        "Medium suits a bedside table or a shelf.",
        "Large sits well beside a child on a sofa.",
        "Extra large is a feature piece and takes up space.",
      ] },
      { t: "p", text: "If you are stuck, the Size Finder suggests a size. We do not publish measurements yet, so photos and comparisons are the best guide." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Adding a note" },
      { t: "p", text: "Keep a gift note to one or two lines. Use a first name only. Please do not include a child's surname, school or personal details." },
      { t: "h", text: "If you want it just right" },
      { t: "p", text: "The Gift Finder asks about the occasion and the person, then lists animals that fit. If you have a colour or a detail in mind, the Studio lets you describe it, and we reply on WhatsApp to say what is possible." },
      { t: "p", text: "Whatever you pick, wrap it, write a line and hand it over yourself. That part matters most." },
    ],
    links: [
      { label: "Gifts", href: "/gifts" },
      { label: "Gift Finder", href: "/gifts/finder" },
      { label: "Size Finder", href: "/size-finder" },
      { label: "Custom Studio", href: "/custom/studio" },
      { label: "Giraffes", href: "/shop/giraffe" },
      { label: "Butterflies", href: "/shop/butterfly" },
      { label: "Turtles", href: "/shop/turtle" },
    ],
    cta: { text: "Have an occasion in mind? Tell the Gift Finder and see the ideas.", message: "Hello Mikono Creations, I need a gift for an occasion and would like some ideas.", href: "/gifts/finder" },
    images: [
      { slot: "hero", after: null, brief: "A crocheted giraffe wrapped loosely in patterned cloth on a bed, tag attached, morning light. No people.", altHint: "A crocheted giraffe partly wrapped in patterned cloth on a bed" },
      { slot: "inline-1", after: "A birthday", brief: "A table with a simple cake, one candle and a wrapped gift beside it. No faces.", altHint: "A simple birthday cake with one candle and a wrapped gift on a table" },
      { slot: "inline-2", after: "A thank-you", brief: "A crocheted butterfly in blue and aqua on a windowsill beside a handwritten thank-you card.", altHint: "A crocheted butterfly beside a handwritten thank-you card" },
      { slot: "inline-3", after: "Choosing a size", brief: "Four crocheted lions in a row from largest to smallest on a plain table.", altHint: "Four crocheted lions in a row from largest to smallest" },
    ],
    sources: [],
  },
];
