// Journal batch, part B: 12 posts on sustainability and recycled yarn (pillar C), craft and process (pillar D)
// and makers and impact (pillar E).
//
// Writing rules: plain English at about a grade 6 to 8 reading level, short sentences, facts only from the client
// brief, the photos or the sources listed on each post. No statistics, quotes, names or safety claims.
//
// Type note: Post is imported from ../journal (it is exported there). BatchPost swaps its `blocks` for BatchBlock[]
// and adds batch fields. A BatchPost is therefore NOT assignable to Post until the integration step below is done.
//
// INTEGRATION STEP the renderer must support before these posts go live:
//  1. Block type { t: "image"; slot: "inline-1" | "inline-2" | "inline-3" }. It is a marker. The renderer looks up
//     the entry in post.images with the same slot and shows the photo that was shot for that brief, with altHint as
//     the alt text. ArticleBody currently handles only p, h, ul, ol, note and photo, so add an "image" branch.
//  2. The hero is post.images[0] (slot "hero"). Until the real photo exists, `cover` (an existing PhotoId) is used.
//  3. `links` lists the internal pages that belong with each post. Blocks have no link syntax, so show them as a
//     "Related pages" row under the post. `sources` shows as a "Sources" list under the post (empty list: no row).
//  4. `description` is the meta description (150 characters or fewer). `excerpt` carries the same text for cards.
import type { Block, Post } from "../journal/legacy";

export type ImageMarker = { t: "image"; slot: "inline-1" | "inline-2" | "inline-3" };
export type BatchBlock = Exclude<Block, { t: "photo" }> | ImageMarker;

export type ImageSpec = {
  slot: "hero" | "inline-1" | "inline-2" | "inline-3";
  /** Exact text of the H2 the image sits under. null for the hero. */
  after: string | null;
  /** What the photo should show, in plain words. */
  brief: string;
  /** What a screen reader should hear. */
  altHint: string;
};

export type BatchPost = Omit<Post, "blocks"> & {
  blocks: BatchBlock[];
  /** 150 characters or fewer. */
  description: string;
  /** For example "3 min read". */
  readTime: string;
  tags: string[];
  pillar: "C" | "D" | "E";
  /** Exactly four entries: hero, inline-1, inline-2, inline-3. */
  images: ImageSpec[];
  /** Pages behind factual claims. Empty where the post uses the client brief alone. */
  sources: string[];
  /** Internal links that belong with the post: routes in app/ or /shop/{product slug}. */
  links: { href: string; label: string }[];
};

export const postsPartB: BatchPost[] = [
  {
    slug: "what-a-second-life-means-for-yarn",
    title: "What a second life means for yarn",
    excerpt: "Mikono says recycled acrylic yarn gives waste materials a new life. Here is what that line means, and where it stops.",
    description: "Mikono says recycled acrylic yarn gives waste materials a new life. Here is what that line means, and where it stops.",
    readTime: "3 min read",
    tag: "Materials",
    tags: ["Recycled yarn", "Reuse", "Materials"],
    pillar: "C",
    cover: "threeGiraffes",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Our animals are crocheted from recycled acrylic yarn. We sum this up in one line: recycled acrylic yarn gives waste materials a new life. A short line can hide a lot. So this post slows it down and says what the line means. It also says where the line stops." },
      { t: "h", text: "The idea in plain words" },
      { t: "p", text: "Think of a school jumper that passes from one child to the next. It was made once. It keeps a second child warm. Nobody had to make a new jumper for that." },
      { t: "p", text: "Yarn can work the same way. If yarn already exists, a maker can use it again. Then nobody has to make new yarn for that job. The material stays in use for longer." },
      { t: "image", slot: "inline-1" },
      { t: "p", text: "People who study waste call this a circular approach. The Ellen MacArthur Foundation lists keeping products and materials in use as one of its main ideas. Reuse, repair and recycling are all ways to do it. Our line is one small case of that idea." },
      { t: "p", text: "The yellows, creams and tans you see in our photos are the colours of the yarn each animal was crocheted in." },
      { t: "h", text: "What the line does not say" },
      { t: "p", text: "We want to be clear about the limits." },
      { t: "ul", items: [
        "It does not say the yarn has stopped being acrylic. Acrylic is still a plastic based fibre, and another post in this journal explains that.",
        "It does not claim any benefit to the environment beyond reuse. We have not measured one.",
        "It does not say where each ball of yarn came from. We have not published that yet.",
        "It does not say waste is gone. Some material was used again. The bigger question of how much gets made is still there.",
      ] },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Why we still say it" },
      { t: "p", text: "A lot of what people buy is used for a short time and then thrown out. We start with material that already exists. A maker in Nairobi turns it into an animal that you can keep for years. That is a small push against waste. It does not fix a big problem. It is a choice a workroom can make, so we make it." },
      { t: "h", text: "Three questions for any recycled claim" },
      { t: "ol", items: [
        "Ask what was recycled. For us, it is acrylic yarn.",
        "Ask how much of the product it covers. On our plain animals, all of the crochet is recycled acrylic yarn.",
        "Ask what is left out. We have not published where the yarn is collected, and we would rather say so than guess.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Use these on any label that says recycled. A seller who answers all three is easier to trust than one who answers none." },
      { t: "p", text: "Our impact page says what we claim about the women and the materials. It says nothing more than we can stand behind. If a question is missing there, message us. We will tell you what we know. We will also tell you when we do not know." },
      { t: "p", text: "A second life is a modest promise. We would rather keep it modest and keep it true." },
    ],
    cta: { text: "Want to know more about the yarn before you choose an animal? Ask us.", message: "Hello Mikono Creations, I read your post about a second life for yarn and would like to ask about the yarn." },
    related: ["acrylic-is-a-plastic-based-fibre", "what-is-recycled-acrylic-yarn"],
    images: [
      { slot: "hero", after: null, brief: "Finished giraffes in cream, yellow and tan on a plain table in daylight, with a few skeins of the real yarn in the foreground. No text in the frame.", altHint: "Crocheted giraffes in cream, yellow and tan on a table, with skeins of yarn in front." },
      { slot: "inline-1", after: "The idea in plain words", brief: "Spools and balls of yarn on a workroom shelf or table, in several colours, taken from close range in natural light.", altHint: "Spools and balls of colourful yarn lined up on a shelf." },
      { slot: "inline-2", after: "What the line does not say", brief: "A ball of yarn in a maker's hand beside the finished animal made in the same colour, hands only.", altHint: "A hand holding a ball of yellow yarn next to a yellow crocheted giraffe." },
      { slot: "inline-3", after: "Three questions for any recycled claim", brief: "A close view of crochet stitches on a tan animal, showing the texture of the yarn up close.", altHint: "Close view of tight crochet stitches in tan yarn." },
    ],
    sources: ["https://www.ellenmacarthurfoundation.org/circular-economy/concept"],
    links: [
      { href: "/impact", label: "Our impact" },
      { href: "/story", label: "Our story" },
      { href: "/shop/giraffe", label: "Giraffe" },
    ],
  },
  {
    slug: "acrylic-is-a-plastic-based-fibre",
    title: "Acrylic is a plastic based fibre: our honest note",
    excerpt: "Acrylic is a plastic based fibre. What that means, why washing sheds tiny fibres, and how we suggest you care for an animal.",
    description: "Acrylic is a plastic based fibre. What that means, why washing sheds tiny fibres, and how we suggest you care for an animal.",
    readTime: "3 min read",
    tag: "Materials",
    tags: ["Acrylic", "Microfibres", "Honest answers"],
    pillar: "C",
    cover: "giraffePortrait",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Let us say it first. Acrylic yarn is a plastic based fibre. It is made from a polymer called polyacrylonitrile, which comes from petroleum. Our animals are crocheted from recycled acrylic yarn, so this post is about our own material." },
      { t: "p", text: "Acrylic fibre has been sold since 1948. People like it because it comes in many colours and is easy to wash." },
      { t: "h", text: "How this sits beside zero plastic" },
      { t: "p", text: "On our plain animals we say zero plastic and nothing detachable. Some readers ask how that fits with a fibre that is plastic based. It is a fair question. We have not published a technical definition. If this matters for your choice, ask us. We will say what we know and what we do not." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What happens in the wash" },
      { t: "p", text: "Synthetic fabrics shed tiny fibres when they are washed in a machine. In 2016, researchers at the University of Plymouth washed different fabrics. Acrylic shed far more fibres than a polyester cotton blend. Some of these fibres pass through sewage treatment and reach rivers and the sea." },
      { t: "p", text: "In 2017 the IUCN, a global conservation group, published a report. It said washing synthetic clothes is a major source of tiny plastic particles in the sea. We are not quoting a share. Numbers like that change with each study." },
      { t: "p", text: "That research looked at washing machines and fabric by the kilo. It did not look at one crocheted animal. We do not know how much any of ours sheds. We only know it is the same family of material, so the same sensible habits apply." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "What we suggest" },
      { t: "p", text: "Our animals are easy to clean. That does not mean they should be washed every week. A brush and a damp cloth do most of the work." },
      { t: "ul", items: [
        "Wash rarely. Brush, wipe or dab a mark instead.",
        "If you must wash, use cool water and a little mild soap. Cooler water releases fewer fibres.",
        "Dry it in the air, in a shady, airy place. A machine dryer adds to the shedding.",
        "Keep it dry and aired between uses so it lasts longer.",
      ] },
      { t: "note", text: "These are general tips for synthetic fabrics. They are not a confirmed Mikono wash method. Our care page will carry our own advice first." },
      { t: "h", text: "The trade off" },
      { t: "p", text: "Acrylic holds colour well and is easy to clean. Those are real reasons people choose it for crochet. Other fibres have costs too. A PBS NewsHour report on laundry notes that cotton and wool clothes also shed fibres. No fibre is free of trade offs." },
      { t: "p", text: "We could have chosen another yarn. We chose to work with what is already out there, and to be honest about what it is. You can decide if that suits you." },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Our case for acrylic is reuse. The yarn already exists. Using it again does not change what the fibre is. It does mean that no new yarn was needed for that job. A person then turns it by hand into an animal made to be kept." },
      { t: "p", text: "You should have the whole picture before you choose. We would rather tell you now than have you find out later." },
    ],
    cta: { text: "Have a question about acrylic, washing or zero plastic? Send it to us.", message: "Hello Mikono Creations, I read your post about acrylic and have a question." },
    related: ["what-is-recycled-acrylic-yarn", "wash-less-keep-longer"],
    images: [
      { slot: "hero", after: null, brief: "Macro photo of crochet stitches on a plain yellow or cream animal, soft daylight, shallow depth of field, so the yarn texture is the subject.", altHint: "Extreme close view of crochet stitches in cream yarn." },
      { slot: "inline-1", after: "How this sits beside zero plastic", brief: "A plain crocheted animal on a table with nothing attached to it, shot from the front, showing a smooth body with no extra parts.", altHint: "A plain crocheted lion standing on a wooden table." },
      { slot: "inline-2", after: "What happens in the wash", brief: "A cloth hanging on a line to dry in open air, with a crocheted animal drying beside it on a rack. No faces.", altHint: "A crocheted animal resting on a drying rack next to a cloth on a line." },
      { slot: "inline-3", after: "The trade off", brief: "A hand brushing dust off a crocheted animal with a soft brush, on a plain table. No soap or water in frame.", altHint: "A hand using a soft brush on a yellow crocheted giraffe." },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Acrylic_fiber",
      "https://www.plymouth.ac.uk/news/washing-clothes-releases-thousands-of-microplastic-particles-into-environment-study-shows",
      "https://iucn.org/news/secretariat/201702/invisible-plastic-particles-textiles-and-tyres-major-source-ocean-pollution-%E2%80%93-iucn-study",
      "https://www.pbs.org/newshour/science/laundry-is-a-top-source-of-microplastic-pollution-heres-how-to-clean-your-clothes-more-sustainably",
    ],
    links: [
      { href: "/care", label: "Care guide" },
      { href: "/impact", label: "Our impact" },
      { href: "/shop/elephant", label: "Elephant" },
    ],
  },
  {
    slug: "textile-waste-around-nairobi",
    title: "Textile waste around Nairobi, and one small reuse",
    excerpt: "Used clothes reach Kenya in bales called mitumba. What reports say about textile waste, and where a crocheted animal fits.",
    description: "Used clothes reach Kenya in bales called mitumba. What reports say about textile waste, and where a crocheted animal fits.",
    readTime: "3 min read",
    tag: "Sustainability",
    tags: ["Textile waste", "Nairobi", "Reuse"],
    pillar: "C",
    cover: "canopyStall",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Many people in Kenya buy clothes from mitumba traders. Mitumba is a Swahili word for bales. Used clothes from overseas arrive pressed into big bundles, and traders sell them on by the bale. This trade gives many people work and clothes they can afford." },
      { t: "p", text: "This post is about the other side of the story, which is waste. We are not experts on it. We have kept to what published reports say. We left out their big numbers, because the figures differ from one report to the next." },
      { t: "h", text: "What the reports describe" },
      { t: "p", text: "Greenpeace Africa has written about Gikomba, the big second hand market in Nairobi. Traders there said that some clothes in a bale are too worn or damaged to sell. Clothes that cannot be sold still have to go somewhere. The report says textile waste has blocked drains and polluted the Nairobi River." },
      { t: "image", slot: "inline-1" },
      { t: "p", text: "The United Nations Environment Programme, or UNEP, has been working on guidelines. They aim to tell used clothing that can be sold apart from textile waste. A coalition that includes Kenyan second hand clothing traders asked UNEP to be open about this work." },
      { t: "p", text: "Textile waste is not only a Kenyan matter. Cheap clothes and quick changes in fashion happen worldwide. Clothes sold in one country often began in another. The Kenyan reports show one part of a global pattern." },
      { t: "note", text: "We left out numbers on purpose. If you want them, read the sources listed with this post and check how each one counted." },
      { t: "p", text: "Buying second hand is a normal, sensible choice for many families. We are not against the trade. We only say that some clothes in it end up as waste." },
      { t: "h", text: "Why we mention it" },
      { t: "p", text: "Our animals are made of yarn, not clothes. We have not published where our yarn is collected. So we are not saying our yarn comes from any of the above." },
      { t: "p", text: "We mention it because it is the background to any talk of reuse in Nairobi. Things get made, get used, and then have nowhere to go." },
      { t: "image", slot: "inline-2" },
      { t: "p", text: "What we do say is short. Recycled acrylic yarn gives waste materials a new life. Each animal is crocheted by hand in Nairobi. This work supports 25+ women. Next to a river full of cloth, that is small. We would rather call it small than make it sound big." },
      { t: "h", text: "Small steps you can take" },
      { t: "ul", items: [
        "Mend a hem or sew on a button before buying a new shirt.",
        "Pass clothes to someone who will wear them, not to a bin.",
        "Before you buy, think about how often you will use it.",
        "Look after what you own so it stays in use. Our care page has ideas for crochet.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "If you buy second hand, pick things you will really wear. Clothes left at the back of a cupboard are waste too. None of these steps clears a drain on its own. Many people doing them can change how much gets thrown out." },
      { t: "p", text: "Do you work in textiles or recycling in Nairobi? Write to us and share what you know. We are still learning this subject." },
      { t: "p", text: "Waste is easy to see on a riverbank and easy to miss in a wardrobe. Start with the wardrobe." },
    ],
    cta: { text: "Work in reuse or recycling in Nairobi? We would like to hear from you.", message: "Hello Mikono Creations, I read your post about textile waste and would like to share something." },
    related: ["what-a-second-life-means-for-yarn", "wash-less-keep-longer"],
    images: [
      { slot: "hero", after: null, brief: "A wide daylight view of a Nairobi second hand clothes stall with folded clothes in neat piles, taken with the trader's agreement. No faces in focus and no third party signs.", altHint: "A market stall with neat piles of folded clothes." },
      { slot: "inline-1", after: "What the reports describe", brief: "A tied bale of clothes on the ground at a market, taken from the side in natural light. No faces and no brand labels.", altHint: "A tied bundle of used clothes on the ground at a market." },
      { slot: "inline-2", after: "Why we mention it", brief: "A table with a few crocheted animals and a ball of yarn in daylight, hands only if a person is in frame.", altHint: "Crocheted animals and a ball of yarn on a table." },
      { slot: "inline-3", after: "Small steps you can take", brief: "A mended shirt on a table beside a needle, thread and a small crocheted animal, shot from above.", altHint: "A shirt with a fresh repair, a needle and thread, and a small crocheted animal." },
    ],
    sources: [
      "https://www.greenpeace.org/africa/en/blog/54589/how-fast-fashion-is-fuelling-the-fashion-waste-crisis-in-africa/",
      "https://www.the-star.co.ke/news/2025-10-17-second-hand-clothing-coalition-demands-transparency-in-unep-textile-circularity-project",
      "https://www.greenpeace.org/international/story/53333/how-fast-fashion-is-using-global-south-as-dumping-ground-for-textile-waste/",
    ],
    links: [
      { href: "/impact", label: "Our impact" },
      { href: "/care", label: "Care guide" },
      { href: "/story", label: "Our story" },
    ],
  },
  {
    slug: "wash-less-keep-longer",
    title: "Wash less, keep longer: caring for yarn things",
    excerpt: "General tips to keep blankets, hats and crocheted animals in use for years, with fewer washes and a five minute routine.",
    description: "General tips to keep blankets, hats and crocheted animals in use for years, with fewer washes and a five minute routine.",
    readTime: "3 min read",
    tag: "Care",
    tags: ["Yarn care", "Slow fashion", "Care"],
    pillar: "C",
    cover: "lionPallet",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Yarn things often last longest when you wash them least. This post gives general ideas for blankets, hats and crocheted animals. It is advice for yarn in general. It is not a confirmed Mikono wash method." },
      { t: "note", text: "We have not published a wash method for our animals. When we do, it will go on the care page first." },
      { t: "h", text: "Why washing less helps" },
      { t: "p", text: "Each wash rubs yarn against itself and against the drum. Over time the surface gets rough and the colour can fade. Fewer washes means less wear." },
      { t: "p", text: "Think of a favourite jumper. The one you wash every week fades first. The one you brush and air lasts longer. Yarn is the same." },
      { t: "p", text: "There is a second reason. Synthetic fabrics shed tiny fibres in the wash. A University of Plymouth study found that acrylic shed many more fibres than a polyester cotton blend. PBS NewsHour reports that cotton and wool shed too. Washing less cuts the shedding, whatever the fibre." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "A five minute routine" },
      { t: "ol", items: [
        "Look at the item in good light. Check for marks, loose strands and flat patches.",
        "Brush off dry dust with a soft brush or the flat of your hand.",
        "Dab a mark with a cloth wet with cool water. Try this before soap.",
        "If a strand comes loose, do not pull it. Tuck it back in with a blunt needle or a crochet hook.",
        "Leave the item in open air for an afternoon, out of direct sun.",
      ] },
      { t: "p", text: "Do this once a month for things you handle every day. Do it before you store something for a season. A quick look catches small problems before they grow." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "If it really needs a wash" },
      { t: "p", text: "Some marks will not lift with a dab. For synthetic yarn in general, advice for fewer shed fibres is simple. Use cool water and a little detergent. Wash a full load. Line dry it instead of using a dryer." },
      { t: "p", text: "A full load does not make sense for one small animal. So for us the tip is to keep the machine out of it. Try your method on a small hidden spot first. If colour comes onto the cloth, stop and ask us." },
      { t: "p", text: "Keep bleach away from coloured yarn, because it can strip the colour. Keep hot water away too, since heat can change how yarn feels." },
      { t: "p", text: "Bags and balls sold to catch fibres in the machine catch only part of them, says PBS NewsHour. Some can be rough on delicate fabric. They are not a reason to wash more often." },
      { t: "h", text: "Where to keep your things" },
      { t: "p", text: "Keep yarn things somewhere dry with air around them. Do not shut them in a sealed bag, where damp can collect. Fold a crocheted blanket flat, because hanging can stretch it. Keep long manes, like our lion's, free of squashing." },
      { t: "p", text: "Light matters too. Strong sun can fade colour over many months, so a shelf away from the window is a better home." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Slow fashion in one sentence" },
      { t: "p", text: "Slow fashion is a name for buying less and keeping things longer. The idea suits yarn well. A yarn thing can be brushed, mended and used for years." },
      { t: "p", text: "Pick one thing you own that is made of yarn. Give it five minutes this weekend. Skip the wash." },
    ],
    cta: { text: "Stubborn mark or loose strand on one of our animals? Send us a photo.", message: "Hello Mikono Creations, I need advice on looking after one of your animals. Here is a photo." },
    related: ["how-to-clean-a-crocheted-animal", "acrylic-is-a-plastic-based-fibre"],
    images: [
      { slot: "hero", after: null, brief: "Flat lay on a wooden table: a soft brush, a clean cloth, a blunt needle and a small crocheted lion, shot from above in daylight.", altHint: "A soft brush, a cloth, a needle and a small crocheted lion on a wooden table." },
      { slot: "inline-1", after: "Why washing less helps", brief: "A hand wiping a small mark on a crocheted animal with a barely damp cloth, close up. Hands and animal only.", altHint: "A hand dabbing a crocheted giraffe with a damp cloth." },
      { slot: "inline-2", after: "A five minute routine", brief: "A hand tucking a loose yarn end back into a crocheted animal with a crochet hook, close up.", altHint: "A hand using a crochet hook to tuck a loose strand into a crocheted animal." },
      { slot: "inline-3", after: "Where to keep your things", brief: "Crocheted animals sitting upright on an open wooden shelf with air around them, in soft window light, away from direct sun.", altHint: "Crocheted animals sitting on an open wooden shelf." },
    ],
    sources: [
      "https://www.pbs.org/newshour/science/laundry-is-a-top-source-of-microplastic-pollution-heres-how-to-clean-your-clothes-more-sustainably",
      "https://www.plymouth.ac.uk/news/washing-clothes-releases-thousands-of-microplastic-particles-into-environment-study-shows",
      "https://www.ebsco.com/research-starters/environmental-sciences/slow-fashion/",
    ],
    links: [
      { href: "/care", label: "Care guide" },
      { href: "/shop/lion", label: "Lion" },
      { href: "/size-finder", label: "Size finder" },
    ],
  },
  {
    slug: "amigurumi-what-the-word-means",
    title: "Amigurumi: what the word means",
    excerpt: "A Japanese word for stuffed creatures made from yarn. What it means, how the style is made, and why we say crocheted animals.",
    description: "A Japanese word for stuffed creatures made from yarn. What it means, how the style is made, and why we say crocheted animals.",
    readTime: "3 min read",
    tag: "Craft",
    tags: ["Amigurumi", "Crochet", "Craft words"],
    pillar: "D",
    cover: "octopuses",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "You may have seen the word amigurumi in a craft video or a pattern book. It is Japanese. It names a style of making small stuffed creatures from yarn. This post explains the word, the style, and why we usually say crocheted animals." },
      { t: "h", text: "Taking the word apart" },
      { t: "p", text: "Ami means crocheted or knitted. Kurumi means wrapping. The word is linked to nuigurumi, a Japanese word for a sewn stuffed doll. So amigurumi points to a stuffed shape made with yarn." },
      { t: "p", text: "Amigurumi are usually crocheted, but knitting works too. They have been made in Japan for decades. The style spread to many other countries in the early years of this century. Some people use the word for knitted creatures too. Most of the time, though, they mean a crocheted one." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "How the style is made" },
      { t: "p", text: "A few habits set it apart. The body is worked in a spiral, so there is no seam up one side. The hook is small for the yarn and the stitches are tight. Heads, limbs and ears are often made as separate parts and joined." },
      { t: "p", text: "Why make the stitches tight? Loose stitches leave small gaps. Filling pushes through them, and the animal looks lumpy. Tight stitches also help it keep its shape after months of handling." },
      { t: "p", text: "When you look at one, check for these:" },
      { t: "ul", items: [
        "Tight, even stitches with no gaps.",
        "Parts that were made separately and joined.",
        "Small details, like noses and faces, added last.",
        "A shape that holds up when you squeeze it gently.",
      ] },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Are ours amigurumi?" },
      { t: "p", text: "Our animals are crocheted, shaped in rounds and filled. People who know the word may use it for them. On this site we use plainer names: crocheted animals and stuffed animals. They say the same thing, and you do not need a dictionary. We use the word here once, so you know what it means when you meet it." },
      { t: "p", text: "To see the idea in a small shape, look at our turtle. Its shell winds round in a spiral of stripes. Our octopus has a ruffled skirt. Both are built up from simple pieces." },
      { t: "h", text: "If you want to try it" },
      { t: "p", text: "Start with a ball. A ball needs one skill: working round and round. You add stitches to widen the shape, then take stitches away to close it. Almost every animal begins this way. A head or a body is a ball with a few changes." },
      { t: "p", text: "A small ball with two ears and a stitched face is a good first project. It teaches most of what you need." },
      { t: "p", text: "Count your stitches at the end of each round. It feels slow. It saves you from a wonky shape later." },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Search for beginner amigurumi patterns. Pick one with a photo of each step. Use smooth yarn in a light colour, so you can see your stitches. Dark yarn hides them." },
      { t: "h", text: "A word that travels" },
      { t: "p", text: "Crafts pick up names as they cross borders. Crochet comes from a French word for hook. Amigurumi comes from Japanese. The women who make our animals use the same basic move as crocheters everywhere: a loop pulled through a loop." },
      { t: "p", text: "Amigurumi is a handy word when you search for patterns. You do not need it to enjoy one." },
    ],
    cta: { text: "Looking for a small crocheted animal as a gift? Tell us who it is for.", message: "Hello Mikono Creations, I would like help choosing a small crocheted animal as a gift." },
    related: ["how-crochet-works-one-loop-at-a-time", "from-pattern-to-animal"],
    images: [
      { slot: "hero", after: null, brief: "Top-down photo of three finished small animals (an octopus, a turtle and one more) beside a crochet hook and a ball of yarn on a plain light surface.", altHint: "Small crocheted animals beside a crochet hook and a ball of yarn." },
      { slot: "inline-1", after: "Taking the word apart", brief: "A hand holding a half-finished crocheted ball with the hook still in it, showing the spiral of stitches.", altHint: "A hand holding a half-finished crocheted ball with a hook in it." },
      { slot: "inline-2", after: "How the style is made", brief: "Close view of tight, even stitches on a crocheted turtle shell in mint and cream.", altHint: "Close view of the striped spiral shell of a crocheted turtle." },
      { slot: "inline-3", after: "If you want to try it", brief: "A beginner's practice ball in light yarn on a table beside a hook, a pair of scissors and a stitch marker.", altHint: "A small light coloured crocheted ball beside a hook and scissors." },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Amigurumi",
      "https://en.wikipedia.org/wiki/Crochet",
    ],
    links: [
      { href: "/shop/octopus", label: "Octopus" },
      { href: "/shop/turtle", label: "Turtle" },
      { href: "/gifts/finder", label: "Gift finder" },
    ],
  },
  {
    slug: "how-crochet-works-one-loop-at-a-time",
    title: "One hook, one loop: how crochet works",
    excerpt: "Crochet is a loop pulled through a loop. How a hook makes fabric, rows and rounds, and a short exercise to try at home.",
    description: "Crochet is a loop pulled through a loop. How a hook makes fabric, rows and rounds, and a short exercise to try at home.",
    readTime: "3 min read",
    tag: "Craft",
    tags: ["Crochet", "How it works", "Beginners"],
    pillar: "D",
    cover: "handsGiraffe",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Crochet looks hard until you see the first move. You hold a hook, make a loop, and pull another loop through it. Everything else is that move, repeated in a pattern. A doily and a lion start the same way." },
      { t: "h", text: "The first loop and the chain" },
      { t: "p", text: "A crocheter starts with a slip knot on the hook. She pulls a new loop through the first one. That makes a chain stitch. Repeat it and the chain grows, one loop at a time. The chain is the base for the rows or rounds that follow." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "One live loop" },
      { t: "p", text: "Here is what sets crochet apart from knitting. In most crochet there is only one live loop on the hook at a time. Knitting keeps many loops open on a needle. In crochet each stitch is held by the stitches beside it. So a slipped stitch is usually easier to fix." },
      { t: "h", text: "Rows and rounds" },
      { t: "p", text: "You can make fabric flat, in rows that go back and forth, like a scarf. You can also make it in the round. Rounds make tubes, discs and balls. Crocheted animals are mostly built from rounds, because heads, bodies and legs are round shapes." },
      { t: "p", text: "In a spiral, you keep going round without joining each circle. In joined rounds, you close each circle and start the next." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Hook size and tension" },
      { t: "p", text: "The hook sets the size of each stitch. Thick yarn needs a big hook. Every crocheter also has her own tension, which is how tightly she holds the yarn. Patterns often give a count of stitches across a small sample. If your sample is too big or too small, you change the hook size." },
      { t: "h", text: "Where crochet comes from" },
      { t: "p", text: "The name comes from a French word for hook. Where the craft began is not settled. People have offered several ideas, and none has been proved. The earliest printed instructions that use the word crochet appeared in a Dutch magazine in 1823." },
      { t: "p", text: "Before the nineteenth century, writers often did not tell crochet and knitting apart. That makes older records hard to read." },
      { t: "h", text: "Try it at home" },
      { t: "p", text: "You need a hook and a ball of smooth, light coloured yarn." },
      { t: "ol", items: [
        "Make a slip knot and slide it onto the hook.",
        "Wrap the yarn over the hook and pull it through the loop on the hook. That is one chain.",
        "Repeat until you have a chain of ten. Keep each loop the same size.",
        "Stop and look. Undo it and try again with looser or tighter hands until the chain looks even.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Even loops matter more than speed. Every maker starts here." },
      { t: "p", text: "Next time you hold one of our animals, find a row of stitches near its base. Run a finger along it. Each loop in that row was pulled through by hand." },
    ],
    cta: { text: "Curious how our makers work? Ask a question and we will do our best to answer.", message: "Hello Mikono Creations, I read your post about how crochet works and have a question for the makers." },
    related: ["amigurumi-what-the-word-means", "from-pattern-to-animal"],
    images: [
      { slot: "hero", after: null, brief: "A crochet hook and yarn in a maker's hands mid-stitch, in daylight, with hands and hook in focus. No face needed.", altHint: "Hands crocheting with a hook and yellow yarn." },
      { slot: "inline-1", after: "The first loop and the chain", brief: "A slip knot on a hook and a short chain of stitches lying on a plain cloth, close up.", altHint: "A crochet hook with a short chain of yarn loops on a cloth." },
      { slot: "inline-2", after: "Rows and rounds", brief: "A flat crocheted disc beside a cup-shaped piece and a finished ball, side by side on a table, showing how rounds grow into a shape.", altHint: "A flat crocheted disc, a cup shape and a ball in a row." },
      { slot: "inline-3", after: "Try it at home", brief: "A finished chain of ten loops on a table beside a hook and a ball of light yarn, shot from above.", altHint: "A short crochet chain beside a hook and a ball of light yarn." },
    ],
    sources: ["https://en.wikipedia.org/wiki/Crochet"],
    links: [
      { href: "/makers", label: "Our makers" },
      { href: "/shop/giraffe", label: "Giraffe" },
      { href: "/story", label: "Our story" },
    ],
  },
  {
    slug: "from-pattern-to-animal",
    title: "How a pattern becomes an animal",
    excerpt: "A pattern is a list of counts. In plain terms, how flat circles become heads and legs, and why tension and filling matter.",
    description: "A pattern is a list of counts. In plain terms, how flat circles become heads and legs, and why tension and filling matter.",
    readTime: "3 min read",
    tag: "How it is made",
    tags: ["Patterns", "Process", "Craft"],
    pillar: "D",
    cover: "finishingGiraffe",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "A crocheted animal starts as a few lines of shorthand. They tell the maker how many stitches to make in each round. This post explains in general terms how those lines become a head, a body and legs. We have not published how Mikono writes its own patterns. So we stay with how crochet works in general, and with what our photos show." },
      { t: "h", text: "What a pattern is" },
      { t: "p", text: "A pattern is a recipe made of counts. Round one might say to make six stitches in a ring. Round two might say to put two stitches in each of those. The numbers go up, so the circle gets wider. Each number is a stitch that somebody makes." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "From flat circle to ball" },
      { t: "p", text: "A crocheted disc stays flat because you add stitches in every round. Stop adding, and the sides turn upward to make a cup. Start taking stitches away, and the cup closes into a ball. Widen, work a few plain rounds, then narrow. That is the basic route to a head or a body." },
      { t: "p", text: "A leg or an arm is a narrow tube. It uses the same count round after round, with no adding. An ear or a horn is a small cone. Most animals are a collection of these shapes." },
      { t: "h", text: "Made in parts" },
      { t: "p", text: "Working in parts has a reason. A long neck or a thin leg is easier to shape on its own. You can fix one part without undoing the whole animal." },
      { t: "p", text: "Our photos show this well. Giraffe bodies, horns and muzzles lie in heaps on a table before they are joined. In another photo, a woman sews the face of a tan bear by hand. In a third, a woman trims a lion's mane with scissors. The pieces come first and the details come last." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Tension and filling" },
      { t: "ul", items: [
        "Tight stitches keep the shape firm. They also stop the filling from showing through.",
        "Even tension matters. A loose round next to a tight one makes a dent or a lump.",
        "Filling goes in before the last rounds close. How firmly it is packed changes how the animal feels in your hand.",
      ] },
      { t: "p", text: "What fills our animals has not been published yet. So we cannot say more about ours." },
      { t: "h", text: "Joining and finishing" },
      { t: "p", text: "Parts are joined with a needle and a tail of yarn. A careful maker lines up the stitches so the join looks like part of the design. Loose ends are tucked inside. Then the details go on, and any mane is trimmed to length." },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "We do not say how long one animal takes. We have not confirmed the time, and we would rather leave it out than make up a number." },
      { t: "p", text: "Next time you pick up a crocheted animal, find where the head meets the body. That seam is where the pattern ends and the animal begins." },
    ],
    cta: { text: "Want to see a particular animal in the making? Tell us which and we will share what we can.", message: "Hello Mikono Creations, I would like to see how one of your animals is made." },
    related: ["from-yarn-to-giraffe", "making-a-lion-mane"],
    images: [
      { slot: "hero", after: null, brief: "Loose crocheted pieces laid out in a row on a table in daylight: a head, a body, four legs and two ears, with the yarn beside them.", altHint: "Crocheted animal parts laid out in a row before they are joined." },
      { slot: "inline-1", after: "What a pattern is", brief: "A handwritten or printed list of round counts beside a half-finished crocheted disc and a hook. No brand names visible.", altHint: "A list of stitch counts next to a half-finished crocheted disc." },
      { slot: "inline-2", after: "Made in parts", brief: "Giraffe bodies, horns and muzzles in heaps on a workroom table, with scissors among them.", altHint: "Heaps of yellow giraffe pieces and scissors on a table." },
      { slot: "inline-3", after: "Joining and finishing", brief: "A maker's hands joining a head to a body with a needle, close up, hands and animal only.", altHint: "Hands sewing the head of a crocheted animal onto its body." },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Amigurumi",
      "https://en.wikipedia.org/wiki/Crochet",
    ],
    links: [
      { href: "/makers", label: "Our makers" },
      { href: "/shop/lion", label: "Lion" },
      { href: "/custom/studio", label: "Custom studio" },
    ],
  },
  {
    slug: "why-handmade-differs-from-machine-made",
    title: "Why handmade differs from machine made",
    excerpt: "A fair comparison of the two. What a person adds, what a machine does better, and what to expect from a handmade animal.",
    description: "A fair comparison of the two. What a person adds, what a machine does better, and what to expect from a handmade animal.",
    readTime: "3 min read",
    tag: "Craft",
    tags: ["Handmade", "Craft", "Expectations"],
    pillar: "D",
    cover: "tableOfAnimals",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Put a handmade thing next to a machine made one and people ask which is better. That is the wrong question. They are good at different things. Here is a fair look at both, so you know what you are buying when you choose one of our animals." },
      { t: "h", text: "What a machine does well" },
      { t: "ul", items: [
        "It repeats one shape again and again, so the thousandth copy matches the first.",
        "It works fast.",
        "It can hold a size to a very fine measure.",
      ] },
      { t: "p", text: "If you need a hundred things that are exactly alike, a machine is a sensible choice. We will not pretend otherwise." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What a person adds" },
      { t: "p", text: "A person looks at what is in front of her. She sees a stitch that is too loose and redoes it. She decides where a spot goes on a giraffe. She decides when a mane has been trimmed enough. These are small choices, made again and again all day. That is what handmade means." },
      { t: "p", text: "The cost of this is time. A person works at a person's pace. That is why a handmade animal takes time to make." },
      { t: "p", text: "Look at a market table of our animals. The lions stand together and so do the elephants. You can see they are the same kind. Still, no two are exact twins." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "What that means for you" },
      { t: "p", text: "Handmade comes with variation. Two animals of the same kind and size may differ a little in shade, in the set of an ear, or in the spacing of spots. Another post in this journal explains why colours differ." },
      { t: "p", text: "None of this is a flaw. It is the difference you choose when you choose handmade. It also means your animal is its own animal, and not a copy." },
      { t: "ol", items: [
        "Treat the photo on a shop page as a close guide, not an exact copy.",
        "If one detail matters to you, such as a colour, tell us before you order.",
        "Use the colour filter in the shop, and look at the photo for each colour.",
      ] },
      { t: "h", text: "Can it be mended?" },
      { t: "p", text: "A crocheted animal is made of loops. When a loop works loose, a person can often tuck it back in with a hook or a needle. We say often, not always. If something comes loose on one of ours, send us a photo and we will tell you what we think." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "What we do not claim" },
      { t: "p", text: "We do not say handmade is better made than machine made. We have no test to show that. A good factory can make a very good object. We do not run down other makers either. Our claim is narrower. Each of our animals passed through a pair of hands in Nairobi. That work supports 25+ women." },
      { t: "p", text: "Choose the kind of thing you want. If you want sameness, a machine can give it. If you want to feel the maker's hand in an object, you know where to find us." },
    ],
    cta: { text: "Have a colour or a detail in mind? Tell us before you order.", message: "Hello Mikono Creations, there is one detail on an animal that matters to me. Can we talk about it before I order?" },
    related: ["why-colours-differ-slightly", "from-pattern-to-animal"],
    images: [
      { slot: "hero", after: null, brief: "Two animals of the same kind and colour side by side on a plain table in daylight, showing small differences in stitching and shade. No text.", altHint: "Two yellow crocheted giraffes side by side, similar but not identical." },
      { slot: "inline-1", after: "What a machine does well", brief: "A neat row of identical-looking factory made items on a shelf, such as plain cups, to show what sameness looks like. No brand labels.", altHint: "A row of identical plain white cups on a shelf." },
      { slot: "inline-2", after: "What a person adds", brief: "A maker's hands trimming the mane of a crocheted lion with scissors, close up, hands and lion only.", altHint: "Hands trimming the brown yarn mane of a crocheted lion with scissors." },
      { slot: "inline-3", after: "Can it be mended?", brief: "A close, level view of a seam on a crocheted animal, with a hand tucking a strand back in with a hook.", altHint: "A hand tucking a loose strand into the seam of a crocheted animal." },
    ],
    sources: ["https://en.wikipedia.org/wiki/Crochet"],
    links: [
      { href: "/journal/why-colours-differ-slightly", label: "Why colours differ" },
      { href: "/shop/elephant", label: "Elephant" },
      { href: "/makers", label: "Our makers" },
    ],
  },
  {
    slug: "what-25-plus-women-supported-means",
    title: "What 25+ women supported tells you",
    excerpt: "Mikono supports 25+ women through its work. What that number tells you, what it leaves out, and how to ask about the makers.",
    description: "Mikono supports 25+ women through its work. What that number tells you, what it leaves out, and how to ask about the makers.",
    readTime: "3 min read",
    tag: "Our makers",
    tags: ["Makers", "Impact", "Honest numbers"],
    pillar: "E",
    cover: "stallMaker",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "On our pages you will see the words 25+ women supported. It is one of the few numbers we publish. So it is worth saying what it covers and what it leaves out." },
      { t: "h", text: "What the number says" },
      { t: "p", text: "Mikono Creations was founded in 2019 in Nairobi. Today the business supports 25+ women through its work. The plus sign means at least that many. We use it in place of an exact count." },
      { t: "p", text: "A plus sign says at least. It keeps the line true if the real count is a little higher. We would rather undersell than overstate." },
      { t: "p", text: "The work is crochet. Each animal in the shop is made by hand, with a hook and yarn, in Nairobi. For the women Mikono supports, this work is income for them and their families." },
      { t: "p", text: "Supported is a plain word on purpose. It says the work helps these women earn. It does not say we rescued anyone, and it does not say we changed a life." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What the number leaves out" },
      { t: "p", text: "A number cannot tell you everything. It is a count, and behind it are individual women, each with her own skills. Here is what we have not published, and we would rather say so than guess:" },
      { t: "ul", items: [
        "What each woman is paid.",
        "How many hours she works.",
        "Who does which part of the making.",
        "How long each woman has worked with us.",
      ] },
      { t: "p", text: "We are not hiding anything. The details are just not ready to publish in a form we can stand behind. A made up figure would be worse than none." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "How we talk about the women" },
      { t: "p", text: "We avoid the language of pity. The women are makers. They have skill, they do real work, and the animals exist because of that work. If a page ever sounds as if we are doing someone a favour, we wrote it badly." },
      { t: "p", text: "That is also why we do not give names, quotes or life stories without the person's agreement. A story belongs to the woman who lived it. She decides what is told." },
      { t: "p", text: "We try to follow the same rule in photos. We show the women at work, doing the thing they are good at." },
      { t: "h", text: "How to learn more" },
      { t: "p", text: "The makers page shows women at work. The impact page sets out what we say about the people and the materials. Both stay inside what we can confirm." },
      { t: "p", text: "If you want more, ask. Here are some good places to start:" },
      { t: "ul", items: [
        "Which animal the makers like making most.",
        "What a day in the workroom looks like.",
        "Which part of an animal needs the most care.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "We will share what a maker has agreed to share. We will say plainly what we cannot." },
      { t: "p", text: "A plus sign is an honest place to start. The rest of the story belongs to the makers, and you are welcome to ask for it." },
    ],
    cta: { text: "Want to hear more about the makers? Send us a question.", message: "Hello Mikono Creations, I read about the 25+ women you support and would like to know more." },
    related: ["what-mikono-means", "income-for-families-what-we-can-say"],
    images: [
      { slot: "hero", after: null, brief: "A maker seated with a hook and a half-finished animal in her lap, in natural light, with her agreement, framed from the waist up.", altHint: "A woman seated and crocheting an animal in natural light." },
      { slot: "inline-1", after: "What the number says", brief: "A maker's hands on a crochet hook with yarn, close up, in warm daylight. Hands only.", altHint: "Hands crocheting with a hook and yarn." },
      { slot: "inline-2", after: "What the number leaves out", brief: "A workroom table with finished animals in rows and a few half-finished pieces, no people in frame.", altHint: "A workroom table with rows of finished and half-finished crocheted animals." },
      { slot: "inline-3", after: "How to learn more", brief: "Makers seated together around a table with animal pieces in front of them, taken with their agreement.", altHint: "A group of women seated around a table working on crocheted animals." },
    ],
    sources: [],
    links: [
      { href: "/makers", label: "Our makers" },
      { href: "/impact", label: "Our impact" },
      { href: "/story", label: "Our story" },
    ],
  },
  {
    slug: "mkono-mikono-the-word-behind-our-name",
    title: "Mkono, mikono: the word behind our name",
    excerpt: "Mkono is one hand and mikono is many. A short note on the Swahili word behind our name, and on what hands do all day.",
    description: "Mkono is one hand and mikono is many. A short note on the Swahili word behind our name, and on what hands do all day.",
    readTime: "3 min read",
    tag: "Our name",
    tags: ["Swahili", "Our name", "Makers"],
    pillar: "E",
    cover: "handsStitching",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "Say mkono and you mean one hand. Say mikono and you mean hands, more than one. The second word is our name. This post is a short language note, then a look at what hands do when they make an animal." },
      { t: "h", text: "One word, two numbers" },
      { t: "p", text: "Swahili groups nouns into classes. Each class has its own way of making a plural. Nouns like mkono, which begin with m, take mi for the plural. So mkono becomes mikono. The same change turns mti, a tree, into miti, trees." },
      { t: "p", text: "Mkono can also mean arm. English uses two words for hand and arm. Swahili uses one for both." },
      { t: "note", text: "We are not language teachers. If you speak Swahili and see a better way to put this, please tell us." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "Why a business takes the plural" },
      { t: "p", text: "One hand makes one thing at a time. Mikono Creations supports 25+ women, so the plural is the honest choice. Many hands work in Nairobi to crochet animals. They go to shops, lodges, organisations and homes." },
      { t: "p", text: "A good photo of an animal tells you its colour and its size. It cannot tell you how a loop was pulled or how a face was placed. Those things happen in the hands. That is why we like the word, and why we show the makers at work on the makers page." },
      { t: "h", text: "What hands do when they make an animal" },
      { t: "p", text: "Our photos show some of the jobs. Fingers hold the hook and guide the yarn. A thumb and finger pinch two pieces together for sewing." },
      { t: "p", text: "Scissors trim a lion's mane to an even length. Another hand tucks a loose end out of sight. Think about the order of the work. First the hook and yarn. Then the parts. Then the join. Last, the face. Hands are busy at every step. Crochet is slow work in a way that is easy to forget. Each stitch is a small movement, and an animal is made of very many of them." },
      { t: "image", slot: "inline-2" },
      { t: "ul", items: [
        "Hands make the stitch.",
        "Hands join the parts.",
        "Hands add the face.",
        "Hands trim and check.",
      ] },
      { t: "p", text: "None of these jobs can be rushed. A machine can copy a shape. A person looks at the shape as she goes, and she can change her mind." },
      { t: "h", text: "A few other words you may see here" },
      { t: "p", text: "We use Swahili sparingly and only where we are sure. Karibu means welcome. Asante means thank you, and asante sana means thank you very much. We would rather use three words correctly than twenty carelessly." },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "Try this. Next time you wave to someone, look at your own hand for a moment. It is the tool behind every animal in the shop." },
      { t: "p", text: "Karibu to the journal, and asante for reading." },
    ],
    cta: { text: "Do you speak Swahili and have a note on our wording? We would like to hear it.", message: "Hello Mikono Creations, I read your note on the name and have a comment on the Swahili." },
    related: ["what-mikono-means", "what-25-plus-women-supported-means"],
    images: [
      { slot: "hero", after: null, brief: "Two pairs of hands working at once, one crocheting and one sewing a seam, in warm daylight. Hands only.", altHint: "Two pairs of hands, one crocheting and one sewing, over a table of yarn." },
      { slot: "inline-1", after: "One word, two numbers", brief: "A hand-lettered card with the words mkono and mikono beside a crocheted animal, flat lay on a plain wooden table.", altHint: "A handwritten card reading mkono and mikono next to a crocheted lion." },
      { slot: "inline-2", after: "What hands do when they make an animal", brief: "Scissors trimming a lion's yarn mane, held in one hand, with the lion in the other. Hands and lion only.", altHint: "A hand with scissors trimming the mane of a crocheted lion." },
      { slot: "inline-3", after: "A few other words you may see here", brief: "A maker's open hand holding a finished small crocheted animal, shot close up against a plain wall.", altHint: "An open hand holding a small crocheted animal." },
    ],
    sources: [
      "https://en.wiktionary.org/wiki/mkono",
      "https://kamusi.org/content/noun-classes",
    ],
    links: [
      { href: "/story", label: "Our story" },
      { href: "/makers", label: "Our makers" },
      { href: "/impact", label: "Our impact" },
    ],
  },
  {
    slug: "income-for-families-what-we-can-say",
    title: "Income for families: what we can say",
    excerpt: "How an order becomes work for a maker. What we can say about income for families, and what we will not say until we can show it.",
    description: "How an order becomes work for a maker. What we can say about income for families, and what we will not say until we can show it.",
    readTime: "3 min read",
    tag: "Impact",
    tags: ["Impact", "Income", "Makers"],
    pillar: "E",
    cover: "shelfReady",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "People sometimes ask what buying an animal does for the women who make it. It is a fair question. This post gives the answer we can stand behind. Then it lists the answers we cannot give yet." },
      { t: "h", text: "The link in one line" },
      { t: "p", text: "An order means crochet work to do. That work is income for the women Mikono supports, and income supports their families. Mikono was founded in 2019 and today supports 25+ women this way." },
      { t: "p", text: "Much of what we sell goes to shops, lodges and organisations. An order from a mall shelf or a lodge gift shop becomes work in the workroom. A single order from a home does the same." },
      { t: "p", text: "We say income, not salary or wage, on purpose. We have not published how the women are paid, so we use the widest plain word." },
      { t: "p", text: "Pay and working conditions matter to buyers, and they matter to us. We have not published details, so we make no claims about them. If you need to know more before you order, ask." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "What we will not say" },
      { t: "p", text: "Some impact claims online sound large and cannot be checked. We do not want to add to them. So you will not find these on our pages:" },
      { t: "ul", items: [
        "A figure for what each woman earns.",
        "A promise about what the money pays for.",
        "A sentence that says we have changed a life.",
        "A claim that we pay more than anyone else.",
      ] },
      { t: "p", text: "When we can publish a figure and stand behind it, we will. Until then, the quiet version is the true one." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "Why we avoid the language of rescue" },
      { t: "p", text: "The women who make our animals are makers, not a cause. They bring skill to the table. We try to describe the work as work: a hook, yarn, a pattern, a finished animal. That is a respectful way to talk about anyone's job." },
      { t: "p", text: "Pity makes a person smaller. We would rather you see a maker who is good at her work. That is the picture we try to give in our photos: hands, hooks and finished animals." },
      { t: "h", text: "What you can do" },
      { t: "ol", items: [
        "Order through the shop or the wholesale page, so the work reaches the workroom.",
        "Ask us about the makers. We will answer with what a maker has agreed to share.",
        "Tell us if any wording on our pages sounds like pity. We will fix it.",
      ] },
      { t: "image", slot: "inline-3" },
      { t: "p", text: "You can also help without buying. Share the makers page with a friend. Tell a shop owner you know. Word of mouth brings orders too." },
      { t: "p", text: "The impact page holds the short version of all this. The makers page shows the women at work. Start there." },
      { t: "p", text: "A purchase is a modest thing. It becomes work for somebody. That is all we claim for it." },
    ],
    cta: { text: "Ordering for a shop or an organisation? Start on the wholesale page.", message: "Hello Mikono Creations, I would like to place an order for my shop or organisation." },
    related: ["why-wholesale", "what-25-plus-women-supported-means"],
    images: [
      { slot: "hero", after: null, brief: "Finished animals ready for packing on a workroom table, with hang tags, and a maker's hands closing a box. Natural light.", altHint: "Hands closing a box of finished crocheted animals with hang tags on a table." },
      { slot: "inline-1", after: "The link in one line", brief: "A shop shelf in a Nairobi gift shop with crocheted animals on display, taken with the owner's agreement. No third party signs visible.", altHint: "A gift shop shelf with crocheted giraffes, lions and elephants." },
      { slot: "inline-2", after: "What we will not say", brief: "A plain notebook page with the words what we can say written in marker, beside a crocheted animal. Flat lay.", altHint: "A notebook with handwriting next to a crocheted animal." },
      { slot: "inline-3", after: "What you can do", brief: "Hands tying a hang tag onto a crocheted lion with string, close up.", altHint: "Hands tying a tag onto a crocheted lion." },
    ],
    sources: [],
    links: [
      { href: "/impact", label: "Our impact" },
      { href: "/wholesale", label: "Wholesale" },
      { href: "/makers", label: "Our makers" },
    ],
  },
  {
    slug: "questions-to-ask-about-the-women-who-made-it",
    title: "Questions to ask about the women who made it",
    excerpt: "Five questions a buyer can ask about our makers, with honest answers, and how we share a story only if the maker agrees.",
    description: "Five questions a buyer can ask about our makers, with honest answers, and how we share a story only if the maker agrees.",
    readTime: "3 min read",
    tag: "Our makers",
    tags: ["Makers", "Questions", "Impact"],
    pillar: "E",
    cover: "sewingBear",
    date: "2026-10-03",
    blocks: [
      { t: "p", text: "You are holding a crocheted animal and you wonder who made it. Good. That is the curiosity we hope for. Here are five questions a buyer can fairly ask, and the honest state of our answers." },
      { t: "h", text: "1. Who made this one?" },
      { t: "p", text: "A woman in Nairobi made it, with a hook and recycled acrylic yarn. We do not give names unless a maker has agreed. We do not label single animals with a maker's name. If you want to know more, ask. We will tell you what we can." },
      { t: "image", slot: "inline-1" },
      { t: "h", text: "2. How many women are there?" },
      { t: "p", text: "Mikono supports 25+ women. The plus sign means at least that many. That number is the only count we publish. We do not break it down by age, role or place. We would rather give you one true number than several guesses." },
      { t: "h", text: "3. Can I see them at work?" },
      { t: "p", text: "Yes, in photos. The makers page and this journal show women at work. They crochet on chairs, sew a face onto a bear and trim a lion's mane." },
      { t: "p", text: "In our photos, one woman crochets on a chair beside a finished animal. Another sews on a grey sofa. A third trims a mane among heaps of pieces. Different work happens at the same time." },
      { t: "p", text: "Seeing the work matters to us as well. A photo can show hands, yarn and finished animals, but it cannot show everything. Treat it as a window, not the whole room." },
      { t: "p", text: "Ask us about visits. We have not published a visit policy, so please do not plan one before we reply." },
      { t: "image", slot: "inline-2" },
      { t: "h", text: "4. What does the work give her?" },
      { t: "p", text: "Income, which supports her family. That is as far as we go for now. We do not publish pay, hours or roles. We say so openly instead of guessing." },
      { t: "h", text: "5. Can I hear her story?" },
      { t: "p", text: "Maybe. A story belongs to the person who lived it. We share one only if the maker agrees, and in her own words. If you ask, we will pass your question on and tell you honestly what comes back." },
      { t: "image", slot: "inline-3" },
      { t: "h", text: "Questions we cannot answer yet" },
      { t: "ul", items: [
        "What each maker is paid.",
        "How long each animal takes.",
        "What fills our animals.",
        "Where the yarn is collected.",
      ] },
      { t: "p", text: "These are still being confirmed. We list them so you do not have to wonder." },
      { t: "h", text: "How to ask well" },
      { t: "ul", items: [
        "Ask about the work, such as which animal she enjoys making most.",
        "Skip questions about money, family or hardship. Those are hers to share.",
        "Be patient. A reply from a maker may take time.",
      ] },
      { t: "p", text: "Questions about the work usually bring the best answers. A maker may be glad to talk about her favourite animal. She may prefer to say nothing else. Both are fine." },
      { t: "h", text: "What we do with your questions" },
      { t: "p", text: "Your questions help us improve this site. If many people ask the same thing, we know a page needs a clearer answer. We then work on it. We do not make up an answer to fill a gap." },
      { t: "p", text: "Send the question you most want answered. Other readers may want the same answer." },
    ],
    cta: { text: "Have a question for the makers? Send it and we will pass it on.", message: "Hello Mikono Creations, I have a question for the makers about how an animal is made." },
    related: ["what-25-plus-women-supported-means", "from-yarn-to-giraffe"],
    images: [
      { slot: "hero", after: null, brief: "A maker's hands sewing the face of a crocheted animal on her lap, in warm daylight, with hands and animal in focus.", altHint: "Hands sewing the face of a tan crocheted bear." },
      { slot: "inline-1", after: "1. Who made this one?", brief: "A finished animal on a workroom chair beside a hook and a ball of yarn, no people in frame.", altHint: "A crocheted animal on a chair beside a hook and a ball of yarn." },
      { slot: "inline-2", after: "3. Can I see them at work?", brief: "A woman crocheting on a chair with a finished animal waiting beside her, taken with her agreement, framed from the side.", altHint: "A woman seated on a chair, crocheting, with a crocheted animal beside her." },
      { slot: "inline-3", after: "5. Can I hear her story?", brief: "A flat lay of an animal beside a card with the words ask the makers written by hand, on a plain wooden table.", altHint: "A handwritten card reading ask the makers next to a crocheted animal." },
    ],
    sources: [],
    links: [
      { href: "/makers", label: "Our makers" },
      { href: "/impact", label: "Our impact" },
      { href: "/contact", label: "Contact" },
    ],
  },
];
