// GENERATED by scripts/build-cast.mjs. Do not edit by hand.
export const SPRITES = {
 "butterfly": {
  "animal": "butterfly",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/butterfly.svg?v=5cfd961e",
  "bytes": 3529,
  "parts": [
   "fx-eyes",
   "fx-wing"
  ],
  "weak": false
 },
 "elephant": {
  "animal": "elephant",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/elephant.svg?v=2ddf7119",
  "bytes": 3479,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail",
   "fx-trunk"
  ],
  "weak": false
 },
 "giraffe": {
  "animal": "giraffe",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/giraffe.svg?v=3a975e27",
  "bytes": 5483,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "hippo": {
  "animal": "hippo",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/hippo.svg?v=21883526",
  "bytes": 3652,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "lion": {
  "animal": "lion",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/lion.svg?v=9260d3cb",
  "bytes": 4311,
  "parts": [
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "monkey": {
  "animal": "monkey",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/monkey.svg?v=f4fbd704",
  "bytes": 4379,
  "parts": [
   "fx-arm-l",
   "fx-arm-r",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "octopus": {
  "animal": "octopus",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/octopus.svg?v=1422bd73",
  "bytes": 4744,
  "parts": [
   "fx-arm",
   "fx-eyes",
   "fx-head"
  ],
  "weak": false
 },
 "rabbit": {
  "animal": "rabbit",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/rabbit.svg?v=9d6235f4",
  "bytes": 4667,
  "parts": [
   "fx-arm-l",
   "fx-arm-r",
   "fx-ear",
   "fx-ear-l",
   "fx-ear-r",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "rhino": {
  "animal": "rhino",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/rhino.svg?v=c12d1620",
  "bytes": 3482,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "turtle": {
  "animal": "turtle",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/turtle.svg?v=ca072dbd",
  "bytes": 3678,
  "parts": [
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "yarn": {
  "animal": "yarn",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/yarn.svg?v=652bd665",
  "bytes": 3039,
  "parts": [
   "fx-eyes",
   "fx-tail"
  ],
  "weak": false
 },
 "zebra": {
  "animal": "zebra",
  "pose": "default",
  "group": "cast",
  "kind": "animal",
  "url": "/fx/cast/zebra.svg?v=1fc23cd4",
  "bytes": 5212,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "bee-fly": {
  "animal": "bee",
  "pose": "fly",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/bee-fly.svg?v=be4fd32f",
  "bytes": 3469,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-wing"
  ],
  "weak": false
 },
 "bee-wave": {
  "animal": "bee",
  "pose": "wave",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/bee-wave.svg?v=295eee4e",
  "bytes": 3874,
  "parts": [
   "fx-arm",
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-wing"
  ],
  "weak": false
 },
 "buffalo-peek": {
  "animal": "buffalo",
  "pose": "peek",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/buffalo-peek.svg?v=abeac879",
  "bytes": 3912,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head"
  ],
  "weak": false
 },
 "buffalo-stand": {
  "animal": "buffalo",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/buffalo-stand.svg?v=2281e190",
  "bytes": 4774,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-tail"
  ],
  "weak": true
 },
 "bush-baby-sit": {
  "animal": "bush-baby",
  "pose": "sit",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/bush-baby-sit.svg?v=e9a224dc",
  "bytes": 4646,
  "parts": [
   "fx-arm",
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "bush-baby-sleep": {
  "animal": "bush-baby",
  "pose": "sleep",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/bush-baby-sleep.svg?v=380749d9",
  "bytes": 3002,
  "parts": [
   "fx-body",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "cat-sleep": {
  "animal": "cat",
  "pose": "sleep",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/cat-sleep.svg?v=a767c323",
  "bytes": 3315,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-head",
   "fx-tail"
  ],
  "weak": false
 },
 "cat-walk": {
  "animal": "cat",
  "pose": "walk",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/cat-walk.svg?v=352e55d0",
  "bytes": 4786,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "chameleon-perch": {
  "animal": "chameleon",
  "pose": "perch",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/chameleon-perch.svg?v=bf514106",
  "bytes": 4731,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-b",
   "fx-leg-f",
   "fx-tail"
  ],
  "weak": false
 },
 "chameleon-zap": {
  "animal": "chameleon",
  "pose": "zap",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/chameleon-zap.svg?v=5abd4204",
  "bytes": 5288,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-b",
   "fx-leg-f",
   "fx-tail",
   "fx-tongue"
  ],
  "weak": false
 },
 "cheetah-sprint": {
  "animal": "cheetah",
  "pose": "sprint",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/cheetah-sprint.svg?v=48630b0b",
  "bytes": 5666,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "cheetah-stand": {
  "animal": "cheetah",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/cheetah-stand.svg?v=c6aff747",
  "bytes": 5754,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "chick-hatch": {
  "animal": "chick",
  "pose": "hatch",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/chick-hatch.svg?v=f684eb4c",
  "bytes": 2757,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-wing"
  ],
  "weak": false
 },
 "chick-stand": {
  "animal": "chick",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/chick-stand.svg?v=5118eda4",
  "bytes": 3415,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-tail",
   "fx-wing"
  ],
  "weak": false
 },
 "crocodile-float": {
  "animal": "crocodile",
  "pose": "float",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/crocodile-float.svg?v=ebc4cf9c",
  "bytes": 3418,
  "parts": [
   "fx-eyes",
   "fx-head",
   "fx-ripple",
   "fx-tail"
  ],
  "weak": false
 },
 "crocodile-stand": {
  "animal": "crocodile",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/crocodile-stand.svg?v=a39c883e",
  "bytes": 3573,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-tail"
  ],
  "weak": false
 },
 "dik-dik-peek": {
  "animal": "dik-dik",
  "pose": "peek",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/dik-dik-peek.svg?v=2698f501",
  "bytes": 2949,
  "parts": [
   "fx-ear",
   "fx-eyes",
   "fx-head"
  ],
  "weak": false
 },
 "dik-dik-stand": {
  "animal": "dik-dik",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/dik-dik-stand.svg?v=21f01773",
  "bytes": 4187,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": true
 },
 "dog-sit": {
  "animal": "dog",
  "pose": "sit",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/dog-sit.svg?v=2dc12f1b",
  "bytes": 4014,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "dog-stand": {
  "animal": "dog",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/dog-stand.svg?v=7a1e166f",
  "bytes": 4579,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "flamingo-one-leg": {
  "animal": "flamingo-one",
  "pose": "leg",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/flamingo-one-leg.svg?v=11d0853b",
  "bytes": 3363,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-neck"
  ],
  "weak": false
 },
 "flamingo-stand": {
  "animal": "flamingo",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/flamingo-stand.svg?v=fe523f3f",
  "bytes": 3345,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-neck"
  ],
  "weak": false
 },
 "goat-climb": {
  "animal": "goat",
  "pose": "climb",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/goat-climb.svg?v=4aaf7f40",
  "bytes": 5071,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "goat-stand": {
  "animal": "goat",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/goat-stand.svg?v=bde85a08",
  "bytes": 4373,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "hornbill-fly": {
  "animal": "hornbill",
  "pose": "fly",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/hornbill-fly.svg?v=87a1695d",
  "bytes": 3229,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-tail",
   "fx-wing"
  ],
  "weak": false
 },
 "hornbill-perch": {
  "animal": "hornbill",
  "pose": "perch",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/hornbill-perch.svg?v=d945d004",
  "bytes": 3897,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-neck",
   "fx-tail",
   "fx-wing"
  ],
  "weak": false
 },
 "impala-leap": {
  "animal": "impala",
  "pose": "leap",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/impala-leap.svg?v=eb9c9ebb",
  "bytes": 5288,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "impala-stand": {
  "animal": "impala",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/impala-stand.svg?v=93cf3232",
  "bytes": 4813,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "ladybird-crawl": {
  "animal": "ladybird",
  "pose": "crawl",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/ladybird-crawl.svg?v=64e60130",
  "bytes": 3424,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-leg-c"
  ],
  "weak": false
 },
 "ladybird-fly": {
  "animal": "ladybird",
  "pose": "fly",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/ladybird-fly.svg?v=1c66bf77",
  "bytes": 2818,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-wing"
  ],
  "weak": true
 },
 "leopard-branch": {
  "animal": "leopard",
  "pose": "branch",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/leopard-branch.svg?v=eb2dbd97",
  "bytes": 5667,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bn",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "leopard-stand": {
  "animal": "leopard",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/leopard-stand.svg?v=8a9fe0fe",
  "bytes": 5865,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "ostrich-peek": {
  "animal": "ostrich",
  "pose": "peek",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/ostrich-peek.svg?v=c4ba2d7d",
  "bytes": 2617,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-neck"
  ],
  "weak": false
 },
 "ostrich-stand": {
  "animal": "ostrich",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/ostrich-stand.svg?v=79e93d42",
  "bytes": 3868,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-neck",
   "fx-tail",
   "fx-wing"
  ],
  "weak": false
 },
 "prop-acacia-branch": {
  "animal": "prop-acacia-branch",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-acacia-branch.svg?v=42b07c45",
  "bytes": 3339,
  "parts": [
   "fx-branch"
  ],
  "weak": false
 },
 "prop-basket": {
  "animal": "prop-basket",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-basket.svg?v=718d1366",
  "bytes": 2812,
  "parts": [
   "fx-handle"
  ],
  "weak": false
 },
 "prop-flower": {
  "animal": "prop-flower",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-flower.svg?v=231420bf",
  "bytes": 3056,
  "parts": [
   "fx-bloom",
   "fx-eyes"
  ],
  "weak": false
 },
 "prop-grass-tuft": {
  "animal": "prop-grass-tuft",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-grass-tuft.svg?v=b9800850",
  "bytes": 1859,
  "parts": [
   "fx-blades"
  ],
  "weak": false
 },
 "prop-pond-ripple": {
  "animal": "prop-pond-ripple",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-pond-ripple.svg?v=1da16e13",
  "bytes": 1992,
  "parts": [
   "fx-pad",
   "fx-ripple"
  ],
  "weak": false
 },
 "prop-rock": {
  "animal": "prop-rock",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-rock.svg?v=a89be5e2",
  "bytes": 1873,
  "parts": [],
  "weak": false
 },
 "prop-thread-loop": {
  "animal": "prop-thread-loop",
  "pose": "default",
  "group": "cast2",
  "kind": "prop",
  "url": "/fx/cast2/prop-thread-loop.svg?v=20a90a64",
  "bytes": 2300,
  "parts": [
   "fx-thread"
  ],
  "weak": false
 },
 "secretary-bird-stand": {
  "animal": "secretary-bird",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/secretary-bird-stand.svg?v=d6189179",
  "bytes": 4627,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "secretary-bird-wings": {
  "animal": "secretary-bird",
  "pose": "wings",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/secretary-bird-wings.svg?v=879fb979",
  "bytes": 5570,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-a",
   "fx-leg-b",
   "fx-neck",
   "fx-tail",
   "fx-wing"
  ],
  "weak": true
 },
 "tortoise-hide": {
  "animal": "tortoise",
  "pose": "hide",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/tortoise-hide.svg?v=18cadc2a",
  "bytes": 3120,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head"
  ],
  "weak": false
 },
 "tortoise-stand": {
  "animal": "tortoise",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/tortoise-stand.svg?v=dd1bdacd",
  "bytes": 4908,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-neck",
   "fx-tail"
  ],
  "weak": false
 },
 "warthog-peek": {
  "animal": "warthog",
  "pose": "peek",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/warthog-peek.svg?v=b1aa2808",
  "bytes": 3156,
  "parts": [
   "fx-body",
   "fx-ear",
   "fx-eyes",
   "fx-head"
  ],
  "weak": false
 },
 "warthog-stand": {
  "animal": "warthog",
  "pose": "stand",
  "group": "cast2",
  "kind": "animal",
  "url": "/fx/cast2/warthog-stand.svg?v=ffbe88c9",
  "bytes": 4329,
  "parts": [
   "fx-body",
   "fx-eyes",
   "fx-head",
   "fx-leg-bf",
   "fx-leg-bn",
   "fx-leg-ff",
   "fx-leg-fn",
   "fx-tail"
  ],
  "weak": true
 }
} as const;
export type SpriteId = keyof typeof SPRITES;
/** Animals and their poses. A pose of "default" means the original single-pose sprite. */
export const POSES = {"butterfly":["default"],"elephant":["default"],"giraffe":["default"],"hippo":["default"],"lion":["default"],"monkey":["default"],"octopus":["default"],"rabbit":["default"],"rhino":["default"],"turtle":["default"],"yarn":["default"],"zebra":["default"],"bee":["fly","wave"],"buffalo":["peek","stand"],"bush-baby":["sit","sleep"],"cat":["sleep","walk"],"chameleon":["perch","zap"],"cheetah":["sprint","stand"],"chick":["hatch","stand"],"crocodile":["float","stand"],"dik-dik":["peek","stand"],"dog":["sit","stand"],"flamingo-one":["leg"],"flamingo":["stand"],"goat":["climb","stand"],"hornbill":["fly","perch"],"impala":["leap","stand"],"ladybird":["crawl","fly"],"leopard":["branch","stand"],"ostrich":["peek","stand"],"secretary-bird":["stand","wings"],"tortoise":["hide","stand"],"warthog":["peek","stand"]} as const;
export type AnimalName = keyof typeof POSES;
export type PoseOf<A extends AnimalName> = (typeof POSES)[A][number];
export const PROPS = ["prop-acacia-branch","prop-basket","prop-flower","prop-grass-tuft","prop-pond-ripple","prop-rock","prop-thread-loop"] as const;
export type PropName = (typeof PROPS)[number];
/** Poses that look weak in the sprite sheet. Do not use. */
export const WEAK_SPRITES: readonly string[] = ["warthog-stand","buffalo-stand","secretary-bird-wings","ladybird-fly","dik-dik-stand"];
