// Builds components/iconSprite.generated.ts: an SVG sprite of the Phosphor icons the site uses (regular line plus the
// 20% fill layer that "duotone" adds). Icons are drawn with <use>, so the icon data never reaches the JavaScript bundle.
// Run: node scripts/build-icons.mjs   (only needed when the list below changes)
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ICONS = {
  shield: "ShieldCheck", leaf: "Leaf", heart: "Heart", pin: "MapPin", phone: "Phone", info: "Info", check: "Check",
  instagram: "InstagramLogo", facebook: "FacebookLogo", recycle: "Recycle", store: "Storefront", ruler: "Ruler", sparkle: "Sparkle",
  back: "ArrowLeft", people: "Users", camera: "Camera", book: "BookOpen", sliders: "Sliders", package: "Package",
};

function weights(file) {
  const src = readFileSync(join(root, "node_modules/@phosphor-icons/react/dist/defs", file + ".es.js"), "utf8");
  const out = {};
  for (const w of ["duotone", "regular"]) {
    const start = src.indexOf(`"${w}"`);
    const end = src.indexOf("],\n  [", start) > 0 ? src.indexOf("],\n  [", start) : src.length;
    const block = src.slice(start, end);
    out[w] = [...block.matchAll(/\{\s*d:\s*"([^"]+)"(?:,\s*opacity:\s*"([^"]+)")?\s*\}/g)].map((m) => ({ d: m[1], o: m[2] }));
  }
  return out;
}

let sprite = "";
for (const [name, file] of Object.entries(ICONS)) {
  const w = weights(file);
  const line = w.regular.map((p) => `<path d="${p.d}"/>`).join("");
  const fill = w.duotone.filter((p) => p.o).map((p) => `<path d="${p.d}" opacity="${p.o}"/>`).join("");
  if (!line) throw new Error("no paths for " + file);
  sprite += `<symbol id="ph-${name}" viewBox="0 0 256 256">${line}</symbol>`;
  if (fill) sprite += `<symbol id="ph-${name}-f" viewBox="0 0 256 256">${fill}</symbol>`;
}
const names = Object.keys(ICONS);
writeFileSync(join(root, "components/iconSprite.generated.ts"),
  `// Generated by scripts/build-icons.mjs. Do not edit.\nexport const PH_NAMES = ${JSON.stringify(names)} as const;\nexport const PH_SPRITE = ${JSON.stringify(sprite)};\n`);
console.log("icons", names.length, "bytes", sprite.length);
