// Bundles the animal engine (components/fx/engine: index.ts, tier.ts, game.ts) into ONE small classic script, so it can load as a plain file
// the moment the HTML is parsed instead of as a webpack chunk that only starts after React has hydrated.
// Writes:
//   public/fx/e/engine.<hash>.js          minified IIFE, content hashed, served immutable (next.config.ts)
//   components/fx/engine.generated.ts      export const ENGINE_URL
// Run: node scripts/build-engine.mjs   (also part of npm run build:cast, predev and prebuild)
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ts = require('typescript');
const { minify } = require(join(root, 'node_modules/next/dist/compiled/terser/bundle.min.js'));
const dir = join(root, 'components/fx/engine');

const js = (name) => ts.transpileModule(readFileSync(join(dir, name + '.ts'), 'utf8'), {
  compilerOptions: { target: ts.ScriptTarget.ES2019, module: ts.ModuleKind.ESNext, removeComments: false, importsNotUsedAsValues: 0 },
}).outputText;

// A module becomes a function scope that returns its exports; imports become destructuring of the module they name.
function wrap(name, deps) {
  let code = js(name);
  const names = [];
  code = code.replace(/^export\s+(?:async\s+)?(?:function\*?|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm, (m, id) => { names.push(id); return m.replace(/^export\s+/, ''); });
  if (/^export\s*[{*]/m.test(code)) throw new Error(`${name}.ts: use "export const/function" only, the engine bundler does not follow export lists`);
  code = code.replace(/^import\s*\{([^}]*)\}\s*from\s*["']\.\/(\w+)["'];?/gm, (m, list, from) => {
    if (!deps.includes(from)) throw new Error(`${name}.ts imports ./${from}, which the bundler does not know`);
    return list.trim() ? `const {${list}} = __m_${from};` : '';
  });
  code = code.replace(/import\(["']\.\/(\w+)["']\)/g, (m, from) => { if (!deps.includes(from)) throw new Error(`${name}.ts imports ./${from}`); return `Promise.resolve(__m_${from})`; });
  if (/^\s*(import|export)\s/m.test(code)) throw new Error(`${name}.ts still has an import or export after bundling`);
  return `const __m_${name} = (() => {\n${code}\nreturn { ${names.join(', ')} };\n})();\n`;
}
const body = wrap('tier', []) + wrap('game', []) + `(() => {\n${js('index').replace(/^import\s*\{([^}]*)\}\s*from\s*["']\.\/tier["'];?/m, (m, l) => `const {${l}} = __m_tier;`).replace(/import\(["']\.\/game["']\)/g, 'Promise.resolve(__m_game)').replace(/^export\s+(?=function|const|let)/gm, '')}\n})();\n`;
if (/^\s*(import|export)\s/m.test(body)) throw new Error('engine bundle still has an import or export');
const out = await minify(`(function(){"use strict";\n${body}})();`, { compress: { passes: 2 }, mangle: true, format: { comments: false, ascii_only: true } });
if (!out.code) throw new Error('minify produced nothing');
const hash = createHash('sha1').update(out.code).digest('hex').slice(0, 8);
const outDir = join(root, 'public/fx/e');
mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) if (/^engine\..*\.js$/.test(f)) rmSync(join(outDir, f));
writeFileSync(join(outDir, `engine.${hash}.js`), out.code);
writeFileSync(join(root, 'components/fx/engine.generated.ts'), `// GENERATED by scripts/build-engine.mjs. Do not edit by hand.\nexport const ENGINE_URL = "/fx/e/engine.${hash}.js";\n`);
console.log(`engine: ${(Buffer.byteLength(out.code) / 1024).toFixed(1)} KB raw, engine.${hash}.js`);
