// Builds everything the animal layer needs from the sprite files, in one pass.
//   public/fx/cast/*.svg   (12 original animals, one pose each)
//   public/fx/cast2/*.svg  (20 animals with two poses each, plus 7 props)
// Writes:
//   components/fx/cast.generated.ts     SVG strings for inline use. Server only: client code never imports it.
//   components/fx/manifest.generated.ts typed manifest: every sprite by id, with animal, pose, group, URL (content hashed), size, parts.
// Checks (the build fails): a sprite over 6 KB, a duplicate id, a file with no viewBox, an animal with a pose name that is not a word.
// Run: node scripts/build-cast.mjs
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const groups = [
  { dir: 'public/fx/cast', url: '/fx/cast', group: 'cast' },
  { dir: 'public/fx/cast2', url: '/fx/cast2', group: 'cast2' },
];
// Sprites that look weak in the sheet (see strategy/stage2/cast2/CAST2.md). Their other pose is used instead.
const WEAK = ['warthog-stand', 'buffalo-stand', 'secretary-bird-wings', 'ladybird-fly', 'dik-dik-stand'];
const MAX_BYTES = 6 * 1024;

const entries = [];
for (const g of groups) {
  for (const f of readdirSync(join(root, g.dir)).filter((x) => x.endsWith('.svg')).sort()) {
    const id = f.slice(0, -4);
    const raw = readFileSync(join(root, g.dir, f), 'utf8').trim();
    if (raw.length > MAX_BYTES) throw new Error(`${id}.svg is ${raw.length} bytes, over the ${MAX_BYTES} limit`);
    if (!/viewBox="0 0 200 200"/.test(raw)) throw new Error(`${id}.svg has no 200x200 viewBox`);
    const prop = id.startsWith('prop-');
    // cast2 files are <animal>-<pose>; the original cast files are a single pose called "default".
    let animal = id, pose = 'default';
    if (g.group === 'cast2' && !prop) {
      const i = id.lastIndexOf('-');
      animal = id.slice(0, i);
      pose = id.slice(i + 1);
      if (!/^[a-z]+$/.test(pose)) throw new Error(`bad pose name in ${id}`);
    }
    const parts = [...new Set([...raw.matchAll(/class="(fx-[a-z0-9-]+)/g)].map((m) => m[1]))].sort();
    const hash = createHash('sha1').update(raw).digest('hex').slice(0, 8);
    entries.push({ id, animal, pose, group: g.group, kind: prop ? 'prop' : 'animal', url: `${g.url}/${f}?v=${hash}`, bytes: Buffer.byteLength(raw), parts, weak: WEAK.includes(id), raw });
  }
}
const seen = new Set();
for (const e of entries) { if (seen.has(e.id)) throw new Error('duplicate sprite id ' + e.id); seen.add(e.id); }

// ---- inline strings (server only). Ids inside each sprite are tokenised with a section sign so every inlined instance gets its own prefix.
let gen = '// GENERATED by scripts/build-cast.mjs. Do not edit by hand. Server only: client code must not import this file.\n// Ids are tokenised with the section sign; see svgIds.ts.\n\n';
gen += 'export const SVG: Record<string, string> = {\n';
for (const e of entries) {
  const svg = e.raw.replace(/(id="|href="#|url\(#)(\w+)/g, '$1§$2');
  gen += `  ${JSON.stringify(e.id)}: ${JSON.stringify(svg)},\n`;
}
gen += '};\n';
writeFileSync(join(root, 'components/fx/cast.generated.ts'), gen);

// ---- typed manifest (safe for the client: no markup)
const poses = {};
for (const e of entries.filter((x) => x.kind === 'animal')) (poses[e.animal] ||= []).push(e.pose);
const sprites = Object.fromEntries(entries.map((e) => [e.id, { animal: e.animal, pose: e.pose, group: e.group, kind: e.kind, url: e.url, bytes: e.bytes, parts: e.parts, weak: e.weak }]));
let man = '// GENERATED by scripts/build-cast.mjs. Do not edit by hand.\n';
man += `export const SPRITES = ${JSON.stringify(sprites, null, 1)} as const;\n`;
man += `export type SpriteId = keyof typeof SPRITES;\n`;
man += `/** Animals and their poses. A pose of "default" means the original single-pose sprite. */\n`;
man += `export const POSES = ${JSON.stringify(poses)} as const;\n`;
man += `export type AnimalName = keyof typeof POSES;\n`;
man += `export type PoseOf<A extends AnimalName> = (typeof POSES)[A][number];\n`;
man += `export const PROPS = ${JSON.stringify(entries.filter((e) => e.kind === 'prop').map((e) => e.id))} as const;\n`;
man += `export type PropName = (typeof PROPS)[number];\n`;
man += `/** Poses that look weak in the sprite sheet. Do not use. */\n`;
man += `export const WEAK_SPRITES: readonly string[] = ${JSON.stringify(WEAK)};\n`;
writeFileSync(join(root, 'components/fx/manifest.generated.ts'), man);
const total = entries.reduce((a, e) => a + e.bytes, 0);
console.log(`cast: ${entries.length} sprites (${entries.filter((e) => e.kind === 'animal').length} animals in ${Object.keys(poses).length} species, ${entries.filter((e) => e.kind === 'prop').length} props), ${(total / 1024).toFixed(0)} KB raw`);
