// Verifies palette chroma cap (OKLCH 0.13) and the AA pairs from strategy/06 section 2.2.
// Direction B palette. Writes strategy/gates/phase7-tokens-check.md and exits nonzero on failure.
import { writeFileSync } from "node:fs";
import { hexToOklch, contrast } from "./color-lib.mjs";

import { tokens } from "./tokens-data.mjs";
const CAP = 0.13;
const pairs = [
  // Text on the light surfaces
  ["charcoal", "bone", 4.5], ["charcoal", "paper", 4.5], ["charcoal", "oat", 4.5], ["charcoal", "sand", 4.5],
  ["baobab", "bone", 4.5], ["baobab", "paper", 4.5], ["baobab", "oat", 4.5], ["baobab", "sand", 4.5],
  ["stone", "bone", 4.5], ["stone", "paper", 4.5], ["stone", "oat", 4.5], ["stone", "sand", 4.5],
  ["terracotta-deep", "bone", 4.5], ["terracotta-deep", "paper", 4.5], ["terracotta-deep", "oat", 4.5], ["terracotta-deep", "sand", 4.5],
  ["terracotta-deep", "terracotta-tint", 4.5], ["terracotta-deep", "ochre-tint", 4.5],
  ["ochre-deep", "bone", 4.5], ["ochre-deep", "paper", 4.5], ["ochre-deep", "oat", 4.5], ["ochre-deep", "ochre-tint", 4.5],
  ["olive", "bone", 4.5], ["olive-deep", "oat", 4.5], ["olive-deep", "olive-tint", 4.5],
  ["brick", "bone", 4.5], ["brick", "paper", 4.5], ["brick", "oat", 4.5],
  // Buttons and badges
  ["button-text", "terracotta-bot", 4.5], ["button-text", "terracotta-deep", 4.5], ["button-text", "olive-deep", 4.5], ["button-text", "terracotta", 4.5],
  ["bone", "baobab", 4.5], ["bone", "baobab-deep", 4.5], ["paper", "baobab", 4.5],
  // Dusk band: splash and footer
  ["dusk-ink", "dusk", 4.5], ["dusk-ink", "dusk-2", 4.5], ["dusk-soft", "dusk", 4.5], ["dusk-soft", "dusk-2", 4.5],
  ["amber", "dusk", 4.5], ["amber", "dusk-2", 4.5], ["amber-ink", "amber", 4.5],
  // Graphics and focus (3:1)
  ["terracotta", "bone", 3], ["terracotta", "paper", 3], ["terracotta", "oat", 3], ["terracotta-deep", "bone", 3],
  ["line", "bone", 3], ["line", "paper", 3], ["amber", "dusk", 3],
];
const forbidden = [["olive", "oat"], ["line", "sand"], ["stone", "terracotta"]];

let fail = 0;
let out = "# Phase 7 tokens check (Direction B, Daylight Clay Tech)\n\nGenerated by `scripts/tokens-check.mjs`. Chroma cap: OKLCH C <= 0.13 (strategy/07 R3, D29).\n\n## Chroma\n\n| Token | Hex | OKLCH L | C | H | Result |\n|---|---|---|---|---|---|\n";
for (const [k, v] of Object.entries(tokens)) {
  const o = hexToOklch(v);
  const ok = o.C <= CAP;
  if (!ok) fail++;
  out += `| ${k} | ${v} | ${o.L.toFixed(3)} | ${o.C.toFixed(3)} | ${o.H.toFixed(0)} | ${ok ? "PASS" : "FAIL"} |\n`;
}
out += "\nThe accent amber (#E3AE5A) is within the cap and is used for light, glow, icons and dusk band accents only, never as a flat large fill on the light surfaces. #EE9B3E is not used anywhere.\n\n## Contrast pairs\n\n| Foreground | Background | Ratio | Needed | Result |\n|---|---|---|---|---|\n";
for (const [f, b, need] of pairs) {
  const r = contrast(tokens[f], tokens[b]);
  const ok = r >= need;
  if (!ok) fail++;
  out += `| ${f} | ${b} | ${r.toFixed(2)} | ${need} | ${ok ? "PASS" : "FAIL"} |\n`;
}
out += "\n## Forbidden pairs (must stay unused)\n\n| Foreground | Background | Ratio |\n|---|---|---|\n";
for (const [f, b] of forbidden) out += `| ${f} | ${b} | ${contrast(tokens[f], tokens[b]).toFixed(2)} |\n`;
out += `\nOverall: ${fail === 0 ? "PASS" : `FAIL (${fail})`}\n`;
writeFileSync(new URL("../strategy/gates/phase7-tokens-check.md", import.meta.url), out);
console.log(out.split("\n").filter((l) => l.includes("FAIL")).join("\n") || "tokens check: PASS");
process.exit(fail ? 1 : 0);
